# Homework #5

## Ensemble learning

This colaboratory contains Homework #5 of the Machine Learning course, which is due **April 4, midnight (23:59 EEST time)**. To complete the homework, extract **(File -> Download .ipynb)** and submit to the course webpage.


## Submission's rules:

1.   Please, submit only .ipynb that you extract from the Colaboratory.
2. Run your homework exercises before submitting (output should be present, preferably restart the kernel and press run all the cells).
3. Do not change the description of tasks in red (even if there is a typo|mistake|etc).
4. Please, make sure to avoid unnecessary long printouts.
5. Each task should be solved right under the question of the task and not elsewhere.
6. Solutions to both regular and bonus exercises should be submitted in one IPYNB file.

Please, steer clear of copying someone else's work. If you discuss assignments with anyone in the course, please, mention their names here:

Pooh

##List of Homework's exercises:

1.   [Ex1](#scrollTo=ux5PBYkbwewj) - 2 points
2.   [Ex2](#scrollTo=Z5C3GX9eXFF_) - 4 points
3.   [Ex3](#scrollTo=uHQscVCD7rM0) - 4 points
4.   [Bonus 1](#scrollTo=iJeG56t9-jWI) - 1 point
5.   [Bonus 2](#scrollTo=cLoHOqAcu0Q9) - up to 3 points
6.   [Bonus 3](#scrollTo=jdZkblZW7bEp) - up to 3 points (based on quality of presentation)



---


## Homework exercise 1: implement and train a bagging classifier with 3 K-NN models as estimators (2 points)


<font color='red'> In this exercise you will need to use `classify_knn` function from the first practice session to train three different KNN models on three resamples of this dataset. </font>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
def create_random_2c_data (D, N):
  """
  Function create_random_2c_data generates two sets of D dimensional
  points (N points each), one for each class. The first set is sampled from D
  dimensional Gaussian distribution with mean 0 and standard deviation 1. The
  second set is generated from the distribution, with mean 1 and standard
  deviation 1.
  """
  # Generating N points for the first class
  mu_vec1 = np.zeros(D) # creates a vector of zeros, these are averages across each dimension
  cov_mat1 = np.eye(D) # creates a diagonal matrix of size D x D, all values except diagonal are 0
  class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, N)

  # The same stuff as above, just averages are shifted into 1
  mu_vec2 = np.ones(D) # creates a vector of ones
  cov_mat2 = np.eye(D)
  class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, N)

  # a lot of boring things....
  # gluing together two matrices generated above
  data = pd.DataFrame(np.concatenate((class1_sample, class2_sample)))

  # Create names for columns
  data.columns = [ 'x' + str(i) for i in (np.arange(D)+1)]

  # Create a class column
  data['class'] = np.concatenate((np.repeat(0, N), np.repeat(1, N)))

  # This is important for plotting and modelling
  data['class'] = data['class'].astype('category')

  return data

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
np.random.seed(2342347823) # random seed, this number was random, no need to build conspiracies around it

D = 2 # two dimensions
N = 100 # points per class

whole_data = create_random_2c_data(D, N)

# Randomly splitting data into train (60%) and validation (40%)
train, val = train_test_split(whole_data, random_state = 111, test_size = 0.40)

n_bootstraps = 3
np.random.seed(1111)

# creating resamples
resamples = [resample(train, n_samples = len(train), replace=True).index.values for i in range(n_bootstraps)]

# first resample
train_resample1 = train.loc[resamples[0]]

# second resample
train_resample2 = train.loc[resamples[1]]

# third resample
train_resample3 = train.loc[resamples[2]]

<font color='red'> Here, I just convert pandas DataFrame into Numpy arrays that are easier to use list comprehension mechanisms on. </font>

In [ ]:
train1 = np.asarray(train_resample1[['x1','x2']])
labels1 = np.asarray(train_resample1[['class']]).reshape((train_resample1.shape[0]))

train2 = np.asarray(train_resample2[['x1','x2']])
labels2 = np.asarray(train_resample2[['class']]).reshape((train_resample2.shape[0]))

train3 = np.asarray(train_resample3[['x1','x2']])
labels3 = np.asarray(train_resample3[['class']]).reshape((train_resample3.shape[0]))

val_points = np.asarray(val[['x1','x2']])
val_labels = np.asarray(val[['class']]).reshape((val.shape[0]))

<font color='red'>  **(Homework exercise 1- a)** Copy and adapt `classify_knn` function from the first homework and practice session to operate on 2D points. **(0.5 points)**</font>

In [ ]:
def dist(point1, point2): # function dist is also from the first practice session
  # sum of squared coordinate-wise differences under sqrt
  return(np.sqrt(np.sum((point2 - point1)**2)))

def classify_knn(val_point, k, train, labels):

  ##### YOUR CODE STARTS #####
  all_distances = []
  nearest_neighbours = []

  loc_dist = 0

  for i in train:
    loc_dist = dist(val_point,i)
    all_distances.append(loc_dist)

  knn_idx = []

  for i in range(k):
    idx = np.argmin(all_distances)

    knn_idx.append(idx)

    all_distances[idx] = np.inf

  for i in knn_idx:
    nearest_neighbours.append(labels[i])

  counts = np.bincount(nearest_neighbours)

  prediction = np.argmax(counts)

  predicted_classes = []

  for i in range(10):
    idx = np.argmax(counts)
    predicted_classes.append(idx)
    counts[idx] = -1

  ##### YOUR CODE ENDS #####

  return prediction

<font color='red'> Test that the function was adapted correctly by running the following example </font>

In [ ]:
val_point = val_points[1]
print(f'predicted class of the first point is {classify_knn(val_point, 5,  train1, labels1)}, while the true class is {val_labels[1]}')

predicted class of the first point is 0, while the true class is 0

<font color='red'> **(Homework exercise 1- b)** Classify each point from the validation set using `classify_knn` function. Use different resamples and list comprehension. Fix `k` at 5. **(1 point)**</font>

In [ ]:
k = 5

# Use three K-NN models that work on three different resamples

##### YOUR CODE STARTS #####
val['knn1'] = [classify_knn(val_point, 5, train1, labels1) for val_point in val_points]
val['knn2'] = [classify_knn(val_point, 5, train2, labels2) for val_point in val_points]
val['knn3'] = [classify_knn(val_point, 5, train3, labels3) for val_point in val_points]
##### YOUR CODE ENDS #####

<font color='red'> Below aggregate individual predictions using the majority vote approach</font>

In [ ]:
##### YOUR CODE STARTS #####
val['knn_bagging'] = val[['knn1', 'knn2', 'knn3']].mode(axis = 1)
##### YOUR CODE ENDS #####

print(f"Accuracy of hand made bagged ensemble with 3 KNNs is {np.sum(val['knn_bagging'] == val['class'])/len(val[['class']])*100}%")

Accuracy of hand made bagged ensemble with 3 KNNs is 66.25%

<font color='red'> **(Homework exercise 1- c)** Use sklearn `BaggingClassifier` to implement analogous model that uses KNeighborsClassifier as an estimator (with k = 5). Don't forget to use a random state for reproducibility.

Assess its performance on the same validation set and display it. **(0.5 points)**</font>

In [ ]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier

##### YOUR CODE STARTS #####
knn_begger = BaggingClassifier(estimator = KNeighborsClassifier(n_neighbors = 5), n_estimators = 3, random_state=112)
knn_begger.fit(train[['x1', 'x2']], train['class'])
##### YOUR CODE ENDS #####
print(f"Accuracy of sklearn bagging with {3} KNNs {knn_begger.score(val[['x1', 'x2']], val[['class']])*100}%")

KeyError: "None of [Index(['x1', 'x2'], dtype='object')] are in the [columns]"

## Homework exercise 2: eXtreme Gradient Boosting (XGBoost) (4 points)

<font color='red'> Let's finally build for ourselves a new shiny XGBoost model, the most popular algorithm for Kaggle competitions. </font>
<font color='red'>  Since XGBoost truly shines on tabular data, we are going to use the Thyroid Disease Dataset for training an XGboost model. Further details about this dataset can be found at
 [here](https://www.openml.org/search?type=data&status=active&id=40475). </font>

In [ ]:
from sklearn.datasets import fetch_openml

data = fetch_openml(name="thyroid-allhyper")

In [ ]:
#Let's take a look at data
data.data

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V17,V18,V19,V20,V21,V22,V23,V24,V25,V26
0,41.0,1,1,1,1,1,1,1,1,1,...,2,1.30000,2,2.500000,2,125.0,2,1.140000,2,109.000000
1,23.0,1,1,1,1,1,1,1,1,1,...,2,4.10000,2,2.000000,2,102.0,1,0.997912,1,110.787984
2,46.0,2,1,1,1,1,1,1,1,1,...,2,0.98000,1,2.024966,2,109.0,2,0.910000,2,120.000000
3,70.0,1,2,1,1,1,1,1,1,1,...,2,0.16000,2,1.900000,2,175.0,1,0.997912,1,110.787984
4,70.0,1,1,1,1,1,1,1,1,1,...,2,0.72000,2,1.200000,2,61.0,2,0.870000,2,70.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2795,70.0,2,1,1,1,1,1,1,1,1,...,2,2.70000,1,2.024966,2,155.0,2,1.050000,2,148.000000
2796,73.0,2,1,2,1,1,1,1,1,1,...,1,4.67215,2,0.700000,2,63.0,2,0.880000,2,72.000000
2797,75.0,2,1,1,1,1,1,1,1,1,...,1,4.67215,1,2.024966,2,147.0,2,0.800000,2,183.000000
2798,60.0,1,1,1,1,1,1,1,1,1,...,2,1.40000,1,2.024966,2,100.0,2,0.830000,2,121.000000
2799,81.0,1,1,1,1,1,1,1,1,1,...,2,1.20000,2,1.500000,2,114.0,2,0.990000,2,115.000000

In [ ]:
# Types of classes
data.target

0       3
1       1
2       1
3       1
4       5
       ..
2795    5
2796    1
2797    1
2798    1
2799    5
Name: Class, Length: 2800, dtype: category
Categories (5, object): ['1', '2', '3', '4', '5']

In [ ]:
# Number of instances for each class
data.target.value_counts()

Class
1    1632
5     771
3     275
2      91
4      31
Name: count, dtype: int64

<font color='red'> **(Homework exercise 2- a)** Complete the preprocessing steps and train the XGBoost model for the Thyroid Disease classification task.
Find additional information regarding the training of an XGBoost model [here](https://xgboost.readthedocs.io/en/latest/python/python_intro.html) **(1.5 points)** </font>

In [ ]:
# Initial data preparation, which involves spliting the dataset into training, validation, and test sets
# Use 80/10/10 datasplit

##### YOUR CODE STARTS #####
n = data.data.shape[0]

train_end = int(n * 0.8)
val_end = int(n * 0.9)

train = data.data[:train_end]
train_labels = data.target[:train_end].astype(int) - 1

val = data.data[train_end:val_end]
val_labels = data.target[train_end:val_end].astype(int) - 1

test = data.data[val_end:]
test_labels = data.target[val_end:].astype(int) - 1

##### YOUR CODE ENDS #####

In [ ]:
import xgboost as xgb
from sklearn.metrics import accuracy_score

##### YOUR CODE STARTS #####

# XGBoost wants data to be wrapped into special formats
dtrain = xgb.DMatrix(train, label = train_labels, enable_categorical=True)
dval = xgb.DMatrix(val, label = val_labels, enable_categorical=True)
dtest = xgb.DMatrix(test, label = test_labels, enable_categorical=True)

# Define the XGBoost parameters (you can add more parameters if you want)
params = {
    "objective": 'multi:softmax',
    "num_class": 5,
    "eval_metric": 'mlogloss'
}

# Train for training and val for validation
eval_list = [(dtrain, "train"), (dval, "validation")]

# Train the XGBoost model
model = xgb.train(params = params, dtrain = dtrain, evals = eval_list, num_boost_round = 100, early_stopping_rounds = 3)

##### YOUR CODE ENDS #####

[0]	train-mlogloss:0.89034	validation-mlogloss:0.91605
[1]	train-mlogloss:0.80687	validation-mlogloss:0.86184
[2]	train-mlogloss:0.74313	validation-mlogloss:0.81792
[3]	train-mlogloss:0.69586	validation-mlogloss:0.79344
[4]	train-mlogloss:0.65708	validation-mlogloss:0.77418
[5]	train-mlogloss:0.62831	validation-mlogloss:0.76539
[6]	train-mlogloss:0.60163	validation-mlogloss:0.75269
[7]	train-mlogloss:0.57871	validation-mlogloss:0.74611
[8]	train-mlogloss:0.55989	validation-mlogloss:0.73711
[9]	train-mlogloss:0.54238	validation-mlogloss:0.72533
[10]	train-mlogloss:0.52802	validation-mlogloss:0.72346
[11]	train-mlogloss:0.51497	validation-mlogloss:0.72376
[12]	train-mlogloss:0.50425	validation-mlogloss:0.72254
[13]	train-mlogloss:0.49320	validation-mlogloss:0.71851
[14]	train-mlogloss:0.48258	validation-mlogloss:0.72120
[15]	train-mlogloss:0.47419	validation-mlogloss:0.71694
[16]	train-mlogloss:0.46520	validation-mlogloss:0.71736
[17]	train-mlogloss:0.45870	validation-mlogloss:0.71494
[18]	train-mlogloss:0.45198	validation-mlogloss:0.71308
[19]	train-mlogloss:0.44671	validation-mlogloss:0.71345
[20]	train-mlogloss:0.43923	validation-mlogloss:0.71562
[21]	train-mlogloss:0.43418	validation-mlogloss:0.71617

<font color='red'> **(Homework exercise 2- b)**  Make predictions on the test data and evaluate the model **(0.5 points)** </font>

In [ ]:
##### YOUR CODE STARTS #####
res = model.predict(dtest)

print(np.sum(res == test_labels) / len(test_labels))

##### YOUR CODE ENDS #####

0.7607142857142857

<font color='red'> **(Homework exercise 2- c)**  In machine learning, feature importance scores are used to determine the relative importance of each feature in a dataset when building a predictive model. Such scores can be derived from a variety of different models, including ensembles. Explore feature importance of the resulting XGBoost model and report the top five most important features **(0.5 points)** </font>

In [ ]:
##### YOUR CODE STARTS #####
importance = model.get_score(importance_type = "weight")

print(sorted(importance.values(), reverse=True))
print(importance)
# ax = importance.values()
# print(sum(ax))
##### YOUR CODE ENDS #####

[425.0, 367.0, 307.0, 296.0, 275.0, 229.0, 67.0, 46.0, 33.0, 28.0, 27.0, 25.0, 22.0, 20.0, 19.0, 14.0, 13.0, 13.0, 10.0, 10.0, 9.0, 8.0, 5.0, 3.0]
{'V1': 425.0, 'V2': 67.0, 'V3': 46.0, 'V4': 3.0, 'V5': 10.0, 'V6': 28.0, 'V7': 13.0, 'V9': 20.0, 'V10': 14.0, 'V11': 19.0, 'V12': 13.0, 'V13': 5.0, 'V14': 22.0, 'V16': 27.0, 'V17': 25.0, 'V18': 367.0, 'V19': 33.0, 'V20': 229.0, 'V21': 10.0, 'V22': 307.0, 'V23': 8.0, 'V24': 275.0, 'V25': 9.0, 'V26': 296.0}

<font color='red'> **(Homework exercise 2- d)** Train Adaptive Boosting, Gradient Boosting and a simple KNN model from sklearn (KNeighborsClassifier) on the same training data and evaluate on the same test data. For each model use the default hyperparameters (e.g. `n_estimators` or `n_neighbors`). If you do not want to use default parameters, you can use `cross_val_score` to pick the best values for the hyperparameters using training data. Compare the performance of these three models and XGBoost and draw conclusions in a separate text cell  **(1.5 points)** </font>

In [ ]:
# AdaBoostClassifier
%%time
##### YOUR CODE STARTS #####
from sklearn.ensemble import AdaBoostClassifier

model = AdaBoostClassifier()

model.fit(train, train_labels)

res = model.predict(test)

print(f'acc:{np.sum(res == test_labels)/ len(test_labels)}')

##### YOUR CODE ENDS #####

acc:0.6892857142857143
CPU times: user 1.01 s, sys: 4.01 ms, total: 1.02 s
Wall time: 1.16 s

In [ ]:
# GradientBoostingClassifier
%%time
# might take considerable time if trained with default number of n_estimators
##### YOUR CODE STARTS #####
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()

model.fit(train, train_labels)

res = model.predict(test)

print(f'acc:{np.sum(res == test_labels)/ len(test_labels)}')

##### YOUR CODE ENDS #####

acc:0.7642857142857142
CPU times: user 3.63 s, sys: 3.45 ms, total: 3.64 s
Wall time: 6.43 s

In [ ]:
# KNeighborsClassifier
%%time
##### YOUR CODE STARTS #####
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(train, train_labels)

res = model.predict(test)

print(f'acc:{np.sum(res == test_labels)/ len(test_labels)}')


##### YOUR CODE ENDS #####

acc:0.5714285714285714
CPU times: user 53.2 ms, sys: 4.89 ms, total: 58.1 ms
Wall time: 41.2 ms

<font color='red'> How these models compare with each other and to XGBoost? Can you try to elaborate on this difference? </font>

In [ ]:
# Write your comment here:
# The results show that the highest accuracy was achieved by the GradientBoostingClassifier (0.7607), which is equal to the performance of XGBoost.
# The lowest accuracy was obtained by the KNeighborsClassifier (0.5714), as it is the simplest model among those considered.
# The other models are ensemble methods, which explains their better performance compared to KNN. The AdaBoostClassifier demonstrates a moderate result (0.6893)

## Homework exercise 3: Kaggle in-class to predict whether a patient will be readmitted to the hospital within 30 days after discharge (4 points)
<font color='red'> In this exercise we will see how well ensembles work in the real-life problems. Here we are going to work with medical data, and more specifically we will attempt to predict whether a patient will be readmitted to the hospital within 30 days after discharge based on numerical and categorical features. To this end, we have created a corresponding Kaggle in-class competition: https://www.kaggle.com/t/cfc5280da3b847ab8314140f3b5fd61a (this is invitation link). </font>

<font color='red'> **(Homework exercise 3- a)** Getting started: follow the code provided with the Kaggle competition (`sample_notebook.ipynb`) to make the first sample submission using `random_predict` function, Kaggle API or by manually uploading submission file to https://www.kaggle.com/competitions/ml-kse-2026. Report your score. **(0.5 points)** </font>

In [ ]:
import pandas as pd
import numpy as np
import random

<font color='red'> Load `train.csv` and `test.csv` from https://www.kaggle.com/competitions/ml-kse-2026

In [ ]:
from google.colab import files
files.upload();

Saving train.csv to train (1).csv

In [ ]:
files.upload();

Saving test.csv to test (1).csv

In [ ]:
##### YOUR CODE STARTS #####
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
##### YOUR CODE ENDS #####

<font color='red'> Insert your random guesser below:

In [ ]:
##### YOUR CODE STARTS #####
predict = [np.random.randint(0, 2) for i in range(test.shape[0])]
##### YOUR CODE ENDS #####

<font color='red'> Create a sample submission below

In [ ]:
##### YOUR CODE STARTS #####
submission = test[['id']].copy()

submission['target'] = predict

output_path = 'submission_from_notebook.csv'

submission.to_csv(output_path, index=False)
##### YOUR CODE ENDS #####

NameError: name 'predict' is not defined

In [ ]:
!kaggle competitions submit -c ml-kse-2026 -f submission_from_notebook.csv -m "Random guesser submission"

100% 222k/222k [00:00<00:00, 630kB/s]
Successfully submitted to ML@KSE2026

<font color='red'> You can either use Kaggle API below to submit submission file or download file and submit it manually to Kaggle via web interface. </font>

<font color='red'> You need to have an account on Kaggle.com, before you proceed. When you access your kaggle profile, you need to download your API Token from kaggle. It's very easy:
1. Click on your profile icon
2. Go to **Account**
3. In **API** you press **Create Legacy API token**

**Optionally:** You can create not a Legacy type, altough the token preparation in the notebook process will differ

<font color='red'> Now we load the file **kaggle.json** that you have downloaded, into this notebook: </font>

In [ ]:
files.upload(); # upload your kaggle.json file

Saving kaggle.json to kaggle.json

<font color='red'> The next cell moves the file into a separate folder, sets secure access for it and configures your Kaggle profile for this notebook.</font>

In [ ]:
import json

!mkdir /root/.kaggle/
!mv kaggle.json /root/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json
!kaggle config set -n path -v{/content}

- path is now set to: {/content}

<font color='red'> Assuming that you have accepted the rules of the competition, you should be able to make a submission using the following code: </font>

In [ ]:
!kaggle competitions submit -c ml-kse-2026 -f submission_from_notebook.csv -m "2"

100% 222k/222k [00:00<00:00, 1.14MB/s]
400 Client Error: Bad Request for url: https://api.kaggle.com/v1/competitions.CompetitionApiService/CreateSubmission

<font color='red'> What was the score you received? </font>

In [ ]:
# Report your result here:
#  0.40947

<font color='red'> **(Homework exercise 3- b)** Take off: make two more submissions with at least two different ensemble models we have studied. Make sure to perform all necessary data pre-processing steps to accommodate the requirements of these ensemble models (e.g. data imputation and restructuring). To get full points, shortly summarise your pre-processing, models you have selected and rational behind this choice, and finally report your scores. **(2 points)** </font>

In [ ]:
##### YOUR CODE STARTS #####
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_x = train.iloc[:, 1:-1]
train_y = train['target']

train_x = scaler.fit_transform(train_x)

test_x = test.iloc[:, 1:]
test_x = scaler.fit_transform(test_x)


estimators = [
    ('decision_tree', DecisionTreeClassifier(random_state = 42)),
    ('log_reg', LogisticRegression(max_iter = 10000, solver = 'lbfgs'))
]

model = StackingClassifier(estimators)

model.fit(train_x, train_y)

res = model.predict(test_x)

print(sum(res == 1))
##### YOUR CODE ENDS #####

47

In [ ]:
submission = test[['id']].copy()

submission['target'] = res

output_path = 'submission_from_notebook.csv'

submission.to_csv(output_path, index=False)

In [ ]:
print(train.describe())

                f_1           f_2           f_3           f_4           f_5  \
count  65165.000000  65165.000000  65165.000000  65165.000000  65165.000000
mean       2.022374      3.710872      5.752413      4.403376     43.124806
std        1.447320      5.274660      4.050275      2.989682     19.737365
min        1.000000      1.000000      1.000000      1.000000      1.000000
25%        1.000000      1.000000      1.000000      2.000000     31.000000
50%        1.000000      1.000000      7.000000      4.000000     44.000000
75%        3.000000      3.000000      7.000000      6.000000     57.000000
max        8.000000     28.000000     25.000000     14.000000    132.000000

                f_6           f_7           f_8           f_9          f_10  \
count  65165.000000  65165.000000  65165.000000  65165.000000  65165.000000
mean       1.339461     16.024261      0.371963      0.200890      0.635188
std        1.706360      8.103660      1.264854      0.968261      1.269609
min        0.000000      1.000000      0.000000      0.000000      0.000000
25%        0.000000     10.000000      0.000000      0.000000      0.000000
50%        1.000000     15.000000      0.000000      0.000000      0.000000
75%        2.000000     20.000000      0.000000      0.000000      1.000000
max        6.000000     81.000000     42.000000     76.000000     21.000000

       ...    fc_28         fc_29         fc_30         fc_31         fc_32  \
count  ...  65165.0  65165.000000  65165.000000  65165.000000  65165.000000
mean   ...      0.0      1.406829      1.006476      0.000153      0.000015
std    ...      0.0      0.838334      0.081916      0.012387      0.003917
min    ...      0.0      0.000000      0.000000      0.000000      0.000000
25%    ...      0.0      1.000000      1.000000      0.000000      0.000000
50%    ...      0.0      1.000000      1.000000      0.000000      0.000000
75%    ...      0.0      2.000000      1.000000      0.000000      0.000000
max    ...      0.0      3.000000      3.000000      1.000000      1.000000

              fc_33         fc_34         fc_35         fc_36        target
count  65165.000000  65165.000000  65165.000000  65165.000000  65165.000000
mean       0.000031      0.000015      0.539446      0.769125      0.112668
std        0.005540      0.003917      0.498445      0.421396      0.316189
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000      1.000000      0.000000
50%        0.000000      0.000000      1.000000      1.000000      0.000000
75%        0.000000      0.000000      1.000000      1.000000      0.000000
max        1.000000      1.000000      1.000000      1.000000      1.000000

[8 rows x 48 columns]

In [ ]:
print(test.columns)

Index(['id', 'f_1', 'f_2', 'f_3', 'f_4', 'f_5', 'f_6', 'f_7', 'f_8', 'f_9',
       'f_10', 'f_11', 'fc_1', 'fc_2', 'fc_3', 'fc_4', 'fc_5', 'fc_6', 'fc_7',
       'fc_8', 'fc_9', 'fc_10', 'fc_11', 'fc_12', 'fc_13', 'fc_14', 'fc_15',
       'fc_16', 'fc_17', 'fc_18', 'fc_19', 'fc_20', 'fc_21', 'fc_22', 'fc_23',
       'fc_24', 'fc_25', 'fc_26', 'fc_27', 'fc_28', 'fc_29', 'fc_30', 'fc_31',
       'fc_32', 'fc_33', 'fc_34', 'fc_35', 'fc_36'],
      dtype='object')

<font color='red'> Summarise your pre-processing steps, models selected (why these?): </font>

In [ ]:
# Add your comment here:

<font color='red'> **(Homework exercise 3- c)** Reaching superiority: tune the above models or train a new one (does not have to be ensemble) such that you beat Mr.Smart (`mr_smart.csv`) benchmark. If one or both of your models from 3-b are already superior to Mr.Smart, then you should beat them instead. In order to claim the point in this exercise, describe the model, data pre-processing steps and report your score (which should be higher than Mr Smart's and your previous' models). **(1.5 points)** </font>

In [ ]:
##### YOUR CODE STARTS #####
over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

train_x_ov, train_y_ov = over.fit_resample(train_x, train_y)

under = RandomUnderSampler(sampling_strategy = 0.6, random_state = 42)
train_x_over, train_y_over = under.fit_resample(train_x_ov, train_y_ov)

model = xgb.XGBClassifier(n_estimators = 300, max_depth = 3, tree_method = 'hist', random_state = 42, learning_rate = 0.1)

model.fit(train_x_over, train_y_over)

res = model.predict(test_x)
##### YOUR CODE ENDS #####

<font color='red'> Summarise your pre-processing steps, models selected (why these?), and the "special sauce" (what you changed compared to 3-b) below: </font>

In [ ]:
# Add your comment here: I did all perfomance with data which I knew: data augmentation
# (Tomek links, smote random ...), feature engineering ......The best performance was
# achieved using a data balancing strategy that combines random oversampling with
# random undersampling.

## Bonus exercise 3 (up to 3 bonus points depending on presentation): Discrete AdaBoost from scratch

<font color='red'> In the class we have discussed a simplified version of the AdaBoost, the goal of this task is to implement an unabrdiged version of the Discrete AdaBoost classifier following the instructions from the paper [Friedman et al (2000)](https://hastie.su.domains/Papers/AdditiveLogisticRegression/alr.pdf). In a nutshell, AdaBoost classifier assigns initial weights to training examples, fits a weak classifier, and updates the data and classifier weights based on classification accuracy. The process is repeated for each weak estimator. The final strong classifier combines weak classifiers with different weights.</font>

<font color='red'> Implement AdaBoost classifier.

Tips:

- use `DecisionTreeClassifier` from `sklearn` as a weak classifier
- avoid division by zero
- pay attention to the format of data labels.</font>

In [ ]:
from sklearn.tree import DecisionTreeClassifier


class AdaBoost:
  def __init__(self, n_estimators = 50):
    self.n_estimators = n_estimators
    self.estimator_weights = []
    self.models = []

  def fit(self, X, y):
    ##### YOUR CODE STARTS #####

    weight = np.array([1 / len(X) for i in range(len(X))])

    y = [-1 if label == 0 else 1 for label in y]

    for i in range(self.n_estimators):
      model = DecisionTreeClassifier(max_depth = 1)

      model.fit(X, y, sample_weight = weight)

      res = model.predict(X)

      nepravilni = res != y

      error_estimator = np.sum(nepravilni * weight)


      self.estimator_weights.append(np.log((1 - error_estimator) / error_estimator))

      self.models.append(model)


      cm = np.log((1-error_estimator) / error_estimator)

      # weight = [waga * np.exp(cm) if nepravilni[idx] else waga for idx, waga in enumerate(weight)]
      weight = weight * np.exp(cm * nepravilni)

      suma_wag = np.sum(weight)

      weight = weight / suma_wag

    ##### YOUR CODE ENDS #####

  def predict(self, X):
    ##### YOUR CODE STARTS #####

    res = []
    for i in range(self.n_estimators):
      model = self.models[i]

      res.append(model.predict(X))

    res = np.array([pred * w for pred, w in zip(res, self.estimator_weights)])

    res = np.sum(res, axis = 0)

    final_result = [1 if i > 0 else 0 for i in res]

    return np.array(final_result)


    ##### YOUR CODE ENDS #####

<font color='red'> Test your model on the dataset from exercise 3. Report accuracy on the test set and observe how the performance changes with the different number of estimators.</font>

In [ ]:
##### YOUR CODE STARTS #####
model = AdaBoost(n_estimators=50)

model.fit(train_x, train_y)

res = model.predict(test_x)

submission = test[['id']].copy()

submission['target'] = res.astype(int)

output_path = 'submission_from_notebook.csv'

submission.to_csv(output_path, index=False)

!kaggle competitions submit -c ml-kse-2026 -f submission_from_notebook.csv -m "ada from ourself"
##### YOUR CODE ENDS #####

100% 222k/222k [00:00<00:00, 938kB/s]
Successfully submitted to ML@KSE2026

<font color='red'> Use sklearn implementation of AdaBoost classifier with the same parameters as you used for your implementation. Report accuracy on the test set as well. </font>

In [ ]:
##### YOUR CODE STARTS #####
from sklearn.ensemble import AdaBoostClassifier

model = AdaBoostClassifier(n_estimators=50)

model.fit(train_x, train_y)

res = model.predict(test_x)

submission = test[['id']].copy()

submission['target'] = res.astype(int)

output_path = 'submission_from_notebook.csv'

submission.to_csv(output_path, index=False)

!kaggle competitions submit -c ml-kse-2026 -f submission_from_notebook.csv -m "ada from scikit-learn"

##### YOUR CODE ENDS #####

100% 222k/222k [00:00<00:00, 1.08MB/s]
Successfully submitted to ML@KSE2026

<font color='red'> Report difference in results, if there are any. Explain why sklearn's model behaves differently, you might want to take a look at sklearn's [code](https://github.com/scikit-learn/scikit-learn/blob/093e0cf14/sklearn/ensemble/_weight_boosting.py#L341) :)</font>

<font color='red'> Your answer:</font>

Your comments:

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
files.upload();

Saving train.csv to train.csv

In [ ]:
files.upload();

Saving test.csv to test.csv

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train['f_new'] = train['f_2'] * train['f_10']
test['f_new'] = test['f_2'] * test['f_10']


num_cols = [col for col in train.columns if col.startswith('f_')]
cat_cols = [col for col in train.columns if col.startswith('fc_')]

train_y = train['target']
train_x = train.drop(columns=['target', 'id'])

columns_on_train = train_x.columns
test_x = test.drop(columns=['id'])

scaler = StandardScaler()
train_num = scaler.fit_transform(train_x[num_cols])
test_num = scaler.transform(test_x[num_cols])

train_x = np.hstack([train_num, train_x[cat_cols].values])
test_x  = np.hstack([test_num, test_x[cat_cols].values])

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_x = train.drop(columns=['target', 'id'])
train_y = train['target']

train_x = scaler.fit_transform(train_x)

test_x = test.drop(columns=['id'])
test_x = scaler.transform(test_x)

In [ ]:
from imblearn.over_sampling import SMOTE

over = SMOTE(random_state=42)

train_x_over, train_y_over = over.fit_resample(train_x, train_y)

In [ ]:
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

estimators = [
    ('decision_tree', DecisionTreeClassifier(random_state = 42, max_depth = 1)),
    ('log_reg', LogisticRegression(max_iter = 10000, solver = 'lbfgs'))
]

model = StackingClassifier(estimators)

model.fit(train_x, train_y)

res = model.predict(X_test)


print(f1_score(res, y_test, average='macro'))

0.48008550051029186

In [ ]:
from sklearn.model_selection import cross_val_score

depth = [1, 3, 5, 7, 10, 15, 30, 50, 100]

for i in depth:
  model = DecisionTreeClassifier(random_state = 42, max_depth = i)

  scores = cross_val_score(model, train_x, train_y, cv=5, scoring='f1')

  print(f"depth = {i} score: {np.mean(scores)}")

depth = 1 score: 0.8873321568326556
depth = 3 score: 0.8870559349343973
depth = 5 score: 0.8867950586971534
depth = 7 score: 0.8787692779866492
depth = 10 score: 0.8685644134121077
depth = 15 score: 0.8523287040589272
depth = 30 score: 0.7912836645438501
depth = 50 score: 0.7857592265786849
depth = 100 score: 0.7849612522059387

In [ ]:
from sklearn.model_selection import cross_val_score

max_iter = [5, 10, 20, 30, 50, 70, 100, 200, 300, 500, 1000]

for i in max_iter:
  model = LogisticRegression(max_iter = i, solver = 'lbfgs')

  scores = cross_val_score(model, train_x, train_y, cv=5, scoring='f1')

  print(f"depth = {i} score: {np.mean(scores)}")

In [ ]:
import xgboost as xgb

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.25, random_state=0)


over = SMOTE(random_state = 42)

train_x_over, train_y_over = over.fit_resample(X_train, y_train)

n_estim = [2, 3, 5, 8, 12, 15, 20, 30 ,50]

max_depth = [1, 3, 5, 10, 20, 50, 100]


for est in n_estim:
  for depth in max_depth:
    model1 = xgb.XGBClassifier(n_estimators = est, max_depth = depth, tree_method = 'hist')
    model2 = xgb.XGBClassifier(n_estimators = est, max_depth = depth, tree_method = 'hist')

    model1.fit(train_x_over, train_y_over)
    model2.fit(X_train, y_train)

    res1 = model1.predict(X_test)
    res2 = model2.predict(X_test)

    print(f"WithOver: n_estim = {est}, depth = {depth} score: {f1_score(res1, y_test, average='macro')}")
    print(f"n_estim = {est}, depth = {depth} score: {f1_score(res2, y_test, average='macro')}")


# # Train for training and val for validation
# eval_list = [(dtrain, "train"), (dval, "validation")]

# # Train the XGBoost model
# model = xgb.train(params = params, dtrain = dtrain, evals = eval_list, num_boost_round = 100, early_stopping_rounds = 3)

WithOver: n_estim = 2, depth = 1 score: 0.518316043094688
n_estim = 2, depth = 1 score: 0.4695233133628549
WithOver: n_estim = 2, depth = 3 score: 0.5580638049242228
n_estim = 2, depth = 3 score: 0.4695233133628549
WithOver: n_estim = 2, depth = 5 score: 0.5640836459640101
n_estim = 2, depth = 5 score: 0.4695233133628549
WithOver: n_estim = 2, depth = 10 score: 0.5440449109553053
n_estim = 2, depth = 10 score: 0.47420794390339654
WithOver: n_estim = 2, depth = 20 score: 0.5370915562536652
n_estim = 2, depth = 20 score: 0.47632591032062965
WithOver: n_estim = 2, depth = 50 score: 0.537799993245297
n_estim = 2, depth = 50 score: 0.47632591032062965
WithOver: n_estim = 2, depth = 100 score: 0.537799993245297
n_estim = 2, depth = 100 score: 0.47632591032062965
WithOver: n_estim = 3, depth = 1 score: 0.518316043094688
n_estim = 3, depth = 1 score: 0.4695233133628549
WithOver: n_estim = 3, depth = 3 score: 0.5580638049242228
n_estim = 3, depth = 3 score: 0.4695233133628549
WithOver: n_estim = 3, depth = 5 score: 0.5547380367526531
n_estim = 3, depth = 5 score: 0.4710966753529072
WithOver: n_estim = 3, depth = 10 score: 0.5368421219420909
n_estim = 3, depth = 10 score: 0.4782769723875564
WithOver: n_estim = 3, depth = 20 score: 0.5368713781404477
n_estim = 3, depth = 20 score: 0.4816190621442434
WithOver: n_estim = 3, depth = 50 score: 0.5356350212351961
n_estim = 3, depth = 50 score: 0.482096529314041
WithOver: n_estim = 3, depth = 100 score: 0.5356350212351961
n_estim = 3, depth = 100 score: 0.482096529314041
WithOver: n_estim = 5, depth = 1 score: 0.518316043094688
n_estim = 5, depth = 1 score: 0.4695233133628549
WithOver: n_estim = 5, depth = 3 score: 0.5583867559589998
n_estim = 5, depth = 3 score: 0.471661441316225
WithOver: n_estim = 5, depth = 5 score: 0.5558714822260071
n_estim = 5, depth = 5 score: 0.4721701348903251
WithOver: n_estim = 5, depth = 10 score: 0.5326352979260646
n_estim = 5, depth = 10 score: 0.4859910914184466
WithOver: n_estim = 5, depth = 20 score: 0.5268594822661711
n_estim = 5, depth = 20 score: 0.49460969109183883

KeyboardInterrupt:

In [ ]:

from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.25, random_state=0)

spis = []
sampl = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7 , 0.8, 0.9]

depth_max = [1, 2, 3, 5, 7, 10, 25, 50, 100, 200]

n_estim = [2, 3, 5, 7, 10, 15, 20, 30, 50, 100, 150, 200, 300]

for depth1 in depth_max:
  for e1 in n_estim:
    for i1 in sampl:
      for i in sampl:

        if i1 > i:
          continue

        over = RandomOverSampler(random_state = 42, sampling_strategy=i1)

        train_x_ov, train_y_ov = over.fit_resample(X_train, y_train)

        tl = RandomUnderSampler(sampling_strategy = i)
        train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

        model = xgb.XGBClassifier(n_estimators = e1, max_depth = depth1, tree_method = 'hist')

        model.fit(train_x_over, train_y_over)

        res = model.predict(X_test)

        print(f'depth: {depth1}, est: {e1}, over:{i1}, under:{i} - {f1_score(res, y_test, average='macro')}')

        spis.append(f1_score(res, y_test, average='macro'))


print(np.max(spis))

depth: 1, est: 2, over:0.2, under:0.2 - 0.4695233133628549
depth: 1, est: 2, over:0.2, under:0.3 - 0.4695233133628549
depth: 1, est: 2, over:0.2, under:0.4 - 0.4695233133628549
depth: 1, est: 2, over:0.2, under:0.5 - 0.4695233133628549
depth: 1, est: 2, over:0.2, under:0.6 - 0.4695233133628549
depth: 1, est: 2, over:0.2, under:0.7 - 0.5603844651025179
depth: 1, est: 2, over:0.2, under:0.8 - 0.5603844651025179
depth: 1, est: 2, over:0.2, under:0.9 - 0.5603844651025179
depth: 1, est: 2, over:0.3, under:0.3 - 0.4695233133628549
depth: 1, est: 2, over:0.3, under:0.4 - 0.4695233133628549
depth: 1, est: 2, over:0.3, under:0.5 - 0.4695233133628549
depth: 1, est: 2, over:0.3, under:0.6 - 0.4695233133628549
depth: 1, est: 2, over:0.3, under:0.7 - 0.5603844651025179
depth: 1, est: 2, over:0.3, under:0.8 - 0.5603844651025179
depth: 1, est: 2, over:0.3, under:0.9 - 0.5603844651025179
depth: 1, est: 2, over:0.4, under:0.4 - 0.4695233133628549
depth: 1, est: 2, over:0.4, under:0.5 - 0.4695233133628549
depth: 1, est: 2, over:0.4, under:0.6 - 0.4695233133628549
depth: 1, est: 2, over:0.4, under:0.7 - 0.5603844651025179
depth: 1, est: 2, over:0.4, under:0.8 - 0.5603844651025179
depth: 1, est: 2, over:0.4, under:0.9 - 0.5603844651025179
depth: 1, est: 2, over:0.5, under:0.5 - 0.4695233133628549
depth: 1, est: 2, over:0.5, under:0.6 - 0.4695233133628549
depth: 1, est: 2, over:0.5, under:0.7 - 0.5603844651025179
depth: 1, est: 2, over:0.5, under:0.8 - 0.5603844651025179
depth: 1, est: 2, over:0.5, under:0.9 - 0.5603844651025179
depth: 1, est: 2, over:0.6, under:0.6 - 0.4695233133628549
depth: 1, est: 2, over:0.6, under:0.7 - 0.5603844651025179
depth: 1, est: 2, over:0.6, under:0.8 - 0.5603844651025179
depth: 1, est: 2, over:0.6, under:0.9 - 0.5603844651025179
depth: 1, est: 2, over:0.7, under:0.7 - 0.5603844651025179
depth: 1, est: 2, over:0.7, under:0.8 - 0.5603844651025179
depth: 1, est: 2, over:0.7, under:0.9 - 0.5603844651025179
depth: 1, est: 2, over:0.8, under:0.8 - 0.5603844651025179
depth: 1, est: 2, over:0.8, under:0.9 - 0.5603844651025179
depth: 1, est: 2, over:0.9, under:0.9 - 0.5603844651025179
depth: 1, est: 3, over:0.2, under:0.2 - 0.4695233133628549
depth: 1, est: 3, over:0.2, under:0.3 - 0.4695233133628549
depth: 1, est: 3, over:0.2, under:0.4 - 0.4695233133628549
depth: 1, est: 3, over:0.2, under:0.5 - 0.4695233133628549
depth: 1, est: 3, over:0.2, under:0.6 - 0.5301826585600452
depth: 1, est: 3, over:0.2, under:0.7 - 0.5506503578294547
depth: 1, est: 3, over:0.2, under:0.8 - 0.5603844651025179
depth: 1, est: 3, over:0.2, under:0.9 - 0.5603844651025179
depth: 1, est: 3, over:0.3, under:0.3 - 0.4695233133628549
depth: 1, est: 3, over:0.3, under:0.4 - 0.4695233133628549
depth: 1, est: 3, over:0.3, under:0.5 - 0.4695233133628549
depth: 1, est: 3, over:0.3, under:0.6 - 0.5301826585600452
depth: 1, est: 3, over:0.3, under:0.7 - 0.5506503578294547
depth: 1, est: 3, over:0.3, under:0.8 - 0.5603844651025179
depth: 1, est: 3, over:0.3, under:0.9 - 0.518316043094688
depth: 1, est: 3, over:0.4, under:0.4 - 0.4695233133628549
depth: 1, est: 3, over:0.4, under:0.5 - 0.4695233133628549
depth: 1, est: 3, over:0.4, under:0.6 - 0.5301826585600452
depth: 1, est: 3, over:0.4, under:0.7 - 0.5301826585600452
depth: 1, est: 3, over:0.4, under:0.8 - 0.5603844651025179
depth: 1, est: 3, over:0.4, under:0.9 - 0.5603844651025179
depth: 1, est: 3, over:0.5, under:0.5 - 0.4695233133628549
depth: 1, est: 3, over:0.5, under:0.6 - 0.5301826585600452
depth: 1, est: 3, over:0.5, under:0.7 - 0.5603844651025179
depth: 1, est: 3, over:0.5, under:0.8 - 0.5603844651025179
depth: 1, est: 3, over:0.5, under:0.9 - 0.5603844651025179
depth: 1, est: 3, over:0.6, under:0.6 - 0.5301826585600452
depth: 1, est: 3, over:0.6, under:0.7 - 0.5301826585600452
depth: 1, est: 3, over:0.6, under:0.8 - 0.5603844651025179
depth: 1, est: 3, over:0.6, under:0.9 - 0.5603844651025179
depth: 1, est: 3, over:0.7, under:0.7 - 0.5301826585600452
depth: 1, est: 3, over:0.7, under:0.8 - 0.5603844651025179
depth: 1, est: 3, over:0.7, under:0.9 - 0.5603844651025179
depth: 1, est: 3, over:0.8, under:0.8 - 0.5603844651025179
depth: 1, est: 3, over:0.8, under:0.9 - 0.5603844651025179
depth: 1, est: 3, over:0.9, under:0.9 - 0.5603844651025179
depth: 1, est: 5, over:0.2, under:0.2 - 0.4695233133628549
depth: 1, est: 5, over:0.2, under:0.3 - 0.4695233133628549
depth: 1, est: 5, over:0.2, under:0.4 - 0.4695233133628549
depth: 1, est: 5, over:0.2, under:0.5 - 0.5024558379166519
depth: 1, est: 5, over:0.2, under:0.6 - 0.5615482965872904
depth: 1, est: 5, over:0.2, under:0.7 - 0.5603844651025179
depth: 1, est: 5, over:0.2, under:0.8 - 0.5603844651025179
depth: 1, est: 5, over:0.2, under:0.9 - 0.5470855326171111
depth: 1, est: 5, over:0.3, under:0.3 - 0.4695233133628549
depth: 1, est: 5, over:0.3, under:0.4 - 0.4695233133628549
depth: 1, est: 5, over:0.3, under:0.5 - 0.5024558379166519
depth: 1, est: 5, over:0.3, under:0.6 - 0.5301826585600452
depth: 1, est: 5, over:0.3, under:0.7 - 0.5615482965872904
depth: 1, est: 5, over:0.3, under:0.8 - 0.5603844651025179
depth: 1, est: 5, over:0.3, under:0.9 - 0.5470855326171111
depth: 1, est: 5, over:0.4, under:0.4 - 0.4695233133628549
depth: 1, est: 5, over:0.4, under:0.5 - 0.5024558379166519
depth: 1, est: 5, over:0.4, under:0.6 - 0.5301826585600452
depth: 1, est: 5, over:0.4, under:0.7 - 0.5603844651025179
depth: 1, est: 5, over:0.4, under:0.8 - 0.5603844651025179
depth: 1, est: 5, over:0.4, under:0.9 - 0.5470855326171111
depth: 1, est: 5, over:0.5, under:0.5 - 0.5024558379166519
depth: 1, est: 5, over:0.5, under:0.6 - 0.5301826585600452
depth: 1, est: 5, over:0.5, under:0.7 - 0.5635298318520968
depth: 1, est: 5, over:0.5, under:0.8 - 0.5603844651025179
depth: 1, est: 5, over:0.5, under:0.9 - 0.5470855326171111
depth: 1, est: 5, over:0.6, under:0.6 - 0.5301826585600452
depth: 1, est: 5, over:0.6, under:0.7 - 0.5603844651025179
depth: 1, est: 5, over:0.6, under:0.8 - 0.5603844651025179
depth: 1, est: 5, over:0.6, under:0.9 - 0.5470855326171111
depth: 1, est: 5, over:0.7, under:0.7 - 0.5603844651025179
depth: 1, est: 5, over:0.7, under:0.8 - 0.5603844651025179
depth: 1, est: 5, over:0.7, under:0.9 - 0.5470855326171111
depth: 1, est: 5, over:0.8, under:0.8 - 0.5603844651025179
depth: 1, est: 5, over:0.8, under:0.9 - 0.5470855326171111
depth: 1, est: 5, over:0.9, under:0.9 - 0.5470855326171111
depth: 1, est: 7, over:0.2, under:0.2 - 0.4695233133628549
depth: 1, est: 7, over:0.2, under:0.3 - 0.4710966753529072
depth: 1, est: 7, over:0.2, under:0.4 - 0.48990037019270405
depth: 1, est: 7, over:0.2, under:0.5 - 0.5292400235098779
depth: 1, est: 7, over:0.2, under:0.6 - 0.5482373246683243
depth: 1, est: 7, over:0.2, under:0.7 - 0.5643938437125554
depth: 1, est: 7, over:0.2, under:0.8 - 0.5622337217231561
depth: 1, est: 7, over:0.2, under:0.9 - 0.5507658237706246
depth: 1, est: 7, over:0.3, under:0.3 - 0.4710966753529072
depth: 1, est: 7, over:0.3, under:0.4 - 0.5137722836711948
depth: 1, est: 7, over:0.3, under:0.5 - 0.5353814747467881
depth: 1, est: 7, over:0.3, under:0.6 - 0.5615482965872904
depth: 1, est: 7, over:0.3, under:0.7 - 0.5622337217231561
depth: 1, est: 7, over:0.3, under:0.8 - 0.5622337217231561
depth: 1, est: 7, over:0.3, under:0.9 - 0.5470855326171111
depth: 1, est: 7, over:0.4, under:0.4 - 0.5137722836711948
depth: 1, est: 7, over:0.4, under:0.5 - 0.5353814747467881
depth: 1, est: 7, over:0.4, under:0.6 - 0.5353814747467881
depth: 1, est: 7, over:0.4, under:0.7 - 0.5659933416274998
depth: 1, est: 7, over:0.4, under:0.8 - 0.5622337217231561
depth: 1, est: 7, over:0.4, under:0.9 - 0.5470855326171111
depth: 1, est: 7, over:0.5, under:0.5 - 0.5353814747467881
depth: 1, est: 7, over:0.5, under:0.6 - 0.5482373246683243
depth: 1, est: 7, over:0.5, under:0.7 - 0.5659933416274998
depth: 1, est: 7, over:0.5, under:0.8 - 0.5622337217231561
depth: 1, est: 7, over:0.5, under:0.9 - 0.5470855326171111
depth: 1, est: 7, over:0.6, under:0.6 - 0.5482373246683243
depth: 1, est: 7, over:0.6, under:0.7 - 0.5659933416274998
depth: 1, est: 7, over:0.6, under:0.8 - 0.5622337217231561
depth: 1, est: 7, over:0.6, under:0.9 - 0.5470855326171111
depth: 1, est: 7, over:0.7, under:0.7 - 0.5659933416274998
depth: 1, est: 7, over:0.7, under:0.8 - 0.5622337217231561
depth: 1, est: 7, over:0.7, under:0.9 - 0.5470855326171111
depth: 1, est: 7, over:0.8, under:0.8 - 0.5622337217231561
depth: 1, est: 7, over:0.8, under:0.9 - 0.5470855326171111
depth: 1, est: 7, over:0.9, under:0.9 - 0.5470855326171111
depth: 1, est: 10, over:0.2, under:0.2 - 0.4695233133628549
depth: 1, est: 10, over:0.2, under:0.3 - 0.4710966753529072
depth: 1, est: 10, over:0.2, under:0.4 - 0.5076118271526796
depth: 1, est: 10, over:0.2, under:0.5 - 0.530974119748309
depth: 1, est: 10, over:0.2, under:0.6 - 0.5615482965872904
depth: 1, est: 10, over:0.2, under:0.7 - 0.5635561400203233
depth: 1, est: 10, over:0.2, under:0.8 - 0.5622337217231561
depth: 1, est: 10, over:0.2, under:0.9 - 0.5470855326171111
depth: 1, est: 10, over:0.3, under:0.3 - 0.4710966753529072
depth: 1, est: 10, over:0.3, under:0.4 - 0.5223388632543022
depth: 1, est: 10, over:0.3, under:0.5 - 0.5446523997161254
depth: 1, est: 10, over:0.3, under:0.6 - 0.5615482965872904
depth: 1, est: 10, over:0.3, under:0.7 - 0.5659933416274998
depth: 1, est: 10, over:0.3, under:0.8 - 0.5622337217231561
depth: 1, est: 10, over:0.3, under:0.9 - 0.5467198609774827
depth: 1, est: 10, over:0.4, under:0.4 - 0.5167781590012773
depth: 1, est: 10, over:0.4, under:0.5 - 0.5448118594179832
depth: 1, est: 10, over:0.4, under:0.6 - 0.5606785055836337
depth: 1, est: 10, over:0.4, under:0.7 - 0.5659933416274998
depth: 1, est: 10, over:0.4, under:0.8 - 0.5517250818783076
depth: 1, est: 10, over:0.4, under:0.9 - 0.5468157210346769
depth: 1, est: 10, over:0.5, under:0.5 - 0.5326590732653154
depth: 1, est: 10, over:0.5, under:0.6 - 0.5606785055836337
depth: 1, est: 10, over:0.5, under:0.7 - 0.5659933416274998
depth: 1, est: 10, over:0.5, under:0.8 - 0.5630240271080154
depth: 1, est: 10, over:0.5, under:0.9 - 0.5468157210346769
depth: 1, est: 10, over:0.6, under:0.6 - 0.5606785055836337
depth: 1, est: 10, over:0.6, under:0.7 - 0.5659933416274998
depth: 1, est: 10, over:0.6, under:0.8 - 0.5630240271080154
depth: 1, est: 10, over:0.6, under:0.9 - 0.5468157210346769
depth: 1, est: 10, over:0.7, under:0.7 - 0.5659933416274998
depth: 1, est: 10, over:0.7, under:0.8 - 0.5630240271080154
depth: 1, est: 10, over:0.7, under:0.9 - 0.5467198609774827
depth: 1, est: 10, over:0.8, under:0.8 - 0.5630240271080154
depth: 1, est: 10, over:0.8, under:0.9 - 0.5468157210346769
depth: 1, est: 10, over:0.9, under:0.9 - 0.5468157210346769
depth: 1, est: 15, over:0.2, under:0.2 - 0.47265817504319957
depth: 1, est: 15, over:0.2, under:0.3 - 0.5001027701394207
depth: 1, est: 15, over:0.2, under:0.4 - 0.5279494535164826
depth: 1, est: 15, over:0.2, under:0.5 - 0.5327656069419731
depth: 1, est: 15, over:0.2, under:0.6 - 0.564892527734778
depth: 1, est: 15, over:0.2, under:0.7 - 0.5608782914555628
depth: 1, est: 15, over:0.2, under:0.8 - 0.5494398997484925
depth: 1, est: 15, over:0.2, under:0.9 - 0.5464483685221697
depth: 1, est: 15, over:0.3, under:0.3 - 0.48818691390889535
depth: 1, est: 15, over:0.3, under:0.4 - 0.5279338992901464
depth: 1, est: 15, over:0.3, under:0.5 - 0.5370785191323576
depth: 1, est: 15, over:0.3, under:0.6 - 0.565463699202301
depth: 1, est: 15, over:0.3, under:0.7 - 0.5626354808548184
depth: 1, est: 15, over:0.3, under:0.8 - 0.553728418507966
depth: 1, est: 15, over:0.3, under:0.9 - 0.550066056728134
depth: 1, est: 15, over:0.4, under:0.4 - 0.5281254198252187
depth: 1, est: 15, over:0.4, under:0.5 - 0.5450104869957956
depth: 1, est: 15, over:0.4, under:0.6 - 0.5638871948626382
depth: 1, est: 15, over:0.4, under:0.7 - 0.5612441393450767
depth: 1, est: 15, over:0.4, under:0.8 - 0.5532648842997729
depth: 1, est: 15, over:0.4, under:0.9 - 0.5457068095277072
depth: 1, est: 15, over:0.5, under:0.5 - 0.5423394316651776
depth: 1, est: 15, over:0.5, under:0.6 - 0.567542112293429
depth: 1, est: 15, over:0.5, under:0.7 - 0.5636232602071625
depth: 1, est: 15, over:0.5, under:0.8 - 0.5549522478698032
depth: 1, est: 15, over:0.5, under:0.9 - 0.547144238338456
depth: 1, est: 15, over:0.6, under:0.6 - 0.5633537762543516
depth: 1, est: 15, over:0.6, under:0.7 - 0.5637418438960183
depth: 1, est: 15, over:0.6, under:0.8 - 0.5549522478698032
depth: 1, est: 15, over:0.6, under:0.9 - 0.5470247633646872
depth: 1, est: 15, over:0.7, under:0.7 - 0.5624971620771778
depth: 1, est: 15, over:0.7, under:0.8 - 0.5538931237192132
depth: 1, est: 15, over:0.7, under:0.9 - 0.5467025661085627
depth: 1, est: 15, over:0.8, under:0.8 - 0.555204673226177
depth: 1, est: 15, over:0.8, under:0.9 - 0.5453560013507825
depth: 1, est: 15, over:0.9, under:0.9 - 0.5453560013507825
depth: 1, est: 20, over:0.2, under:0.2 - 0.4757461114656018
depth: 1, est: 20, over:0.2, under:0.3 - 0.4993231000620564
depth: 1, est: 20, over:0.2, under:0.4 - 0.5301857172464829
depth: 1, est: 20, over:0.2, under:0.5 - 0.5407478706795822
depth: 1, est: 20, over:0.2, under:0.6 - 0.5618135997994615
depth: 1, est: 20, over:0.2, under:0.7 - 0.562955797713413
depth: 1, est: 20, over:0.2, under:0.8 - 0.5537999492393442
depth: 1, est: 20, over:0.2, under:0.9 - 0.5464919799743327
depth: 1, est: 20, over:0.3, under:0.3 - 0.5004314896235532
depth: 1, est: 20, over:0.3, under:0.4 - 0.5305891426726106
depth: 1, est: 20, over:0.3, under:0.5 - 0.5503749365643131
depth: 1, est: 20, over:0.3, under:0.6 - 0.5643887129452697
depth: 1, est: 20, over:0.3, under:0.7 - 0.5636053934618542
depth: 1, est: 20, over:0.3, under:0.8 - 0.5530261959512643
depth: 1, est: 20, over:0.3, under:0.9 - 0.5436051574906468
depth: 1, est: 20, over:0.4, under:0.4 - 0.5293124483571473
depth: 1, est: 20, over:0.4, under:0.5 - 0.5449920091397057
depth: 1, est: 20, over:0.4, under:0.6 - 0.5632751657479359
depth: 1, est: 20, over:0.4, under:0.7 - 0.562744685224569
depth: 1, est: 20, over:0.4, under:0.8 - 0.5530503154964752
depth: 1, est: 20, over:0.4, under:0.9 - 0.5484916041149009
depth: 1, est: 20, over:0.5, under:0.5 - 0.5483835869786622
depth: 1, est: 20, over:0.5, under:0.6 - 0.5641420872811578
depth: 1, est: 20, over:0.5, under:0.7 - 0.5639136146779387
depth: 1, est: 20, over:0.5, under:0.8 - 0.5540591960412443
depth: 1, est: 20, over:0.5, under:0.9 - 0.5476333251146691
depth: 1, est: 20, over:0.6, under:0.6 - 0.5638605636278723
depth: 1, est: 20, over:0.6, under:0.7 - 0.564029006756406
depth: 1, est: 20, over:0.6, under:0.8 - 0.5548514736649581
depth: 1, est: 20, over:0.6, under:0.9 - 0.5461733747230386
depth: 1, est: 20, over:0.7, under:0.7 - 0.5629663478647969
depth: 1, est: 20, over:0.7, under:0.8 - 0.5559066080546463
depth: 1, est: 20, over:0.7, under:0.9 - 0.5474082989014454
depth: 1, est: 20, over:0.8, under:0.8 - 0.5555741097647782
depth: 1, est: 20, over:0.8, under:0.9 - 0.5493657084639681
depth: 1, est: 20, over:0.9, under:0.9 - 0.5468278360602926
depth: 1, est: 30, over:0.2, under:0.2 - 0.4791859237588832
depth: 1, est: 30, over:0.2, under:0.3 - 0.5106219512724758
depth: 1, est: 30, over:0.2, under:0.4 - 0.5279055143900999
depth: 1, est: 30, over:0.2, under:0.5 - 0.545694314168507
depth: 1, est: 30, over:0.2, under:0.6 - 0.5637214325758431
depth: 1, est: 30, over:0.2, under:0.7 - 0.5662893110074068
depth: 1, est: 30, over:0.2, under:0.8 - 0.5551670520979519
depth: 1, est: 30, over:0.2, under:0.9 - 0.5452986432970088
depth: 1, est: 30, over:0.3, under:0.3 - 0.5070413957079432
depth: 1, est: 30, over:0.3, under:0.4 - 0.5279778925240851
depth: 1, est: 30, over:0.3, under:0.5 - 0.5483859324071754
depth: 1, est: 30, over:0.3, under:0.6 - 0.5667081076934213
depth: 1, est: 30, over:0.3, under:0.7 - 0.5678916004564127
depth: 1, est: 30, over:0.3, under:0.8 - 0.5552220631937768
depth: 1, est: 30, over:0.3, under:0.9 - 0.5509761709014346
depth: 1, est: 30, over:0.4, under:0.4 - 0.5313568826611331
depth: 1, est: 30, over:0.4, under:0.5 - 0.549169751397891
depth: 1, est: 30, over:0.4, under:0.6 - 0.5631255587590928
depth: 1, est: 30, over:0.4, under:0.7 - 0.5651370180031722
depth: 1, est: 30, over:0.4, under:0.8 - 0.5551541662966086
depth: 1, est: 30, over:0.4, under:0.9 - 0.5470133779642091
depth: 1, est: 30, over:0.5, under:0.5 - 0.5479898781310697
depth: 1, est: 30, over:0.5, under:0.6 - 0.5637822826974572
depth: 1, est: 30, over:0.5, under:0.7 - 0.5673156782186739
depth: 1, est: 30, over:0.5, under:0.8 - 0.5582267130311487
depth: 1, est: 30, over:0.5, under:0.9 - 0.5505418124730683
depth: 1, est: 30, over:0.6, under:0.6 - 0.5644155464248014
depth: 1, est: 30, over:0.6, under:0.7 - 0.5664063677420531
depth: 1, est: 30, over:0.6, under:0.8 - 0.558277493936983
depth: 1, est: 30, over:0.6, under:0.9 - 0.5515837736885725
depth: 1, est: 30, over:0.7, under:0.7 - 0.5697360217560996
depth: 1, est: 30, over:0.7, under:0.8 - 0.5577380075618068
depth: 1, est: 30, over:0.7, under:0.9 - 0.5503446307367241
depth: 1, est: 30, over:0.8, under:0.8 - 0.5595631714347507
depth: 1, est: 30, over:0.8, under:0.9 - 0.5498059093117602
depth: 1, est: 30, over:0.9, under:0.9 - 0.549486021394063
depth: 1, est: 50, over:0.2, under:0.2 - 0.48006254943429433
depth: 1, est: 50, over:0.2, under:0.3 - 0.5087310624104514
depth: 1, est: 50, over:0.2, under:0.4 - 0.5295883322519819
depth: 1, est: 50, over:0.2, under:0.5 - 0.5524821190198692
depth: 1, est: 50, over:0.2, under:0.6 - 0.570008018628585
depth: 1, est: 50, over:0.2, under:0.7 - 0.5681621305853386
depth: 1, est: 50, over:0.2, under:0.8 - 0.5646826035180743
depth: 1, est: 50, over:0.2, under:0.9 - 0.5487249361741162
depth: 1, est: 50, over:0.3, under:0.3 - 0.5096615619229377
depth: 1, est: 50, over:0.3, under:0.4 - 0.5348896176606125
depth: 1, est: 50, over:0.3, under:0.5 - 0.5542450704444142
depth: 1, est: 50, over:0.3, under:0.6 - 0.5663589730466821
depth: 1, est: 50, over:0.3, under:0.7 - 0.5685871103861033
depth: 1, est: 50, over:0.3, under:0.8 - 0.5626890530152449
depth: 1, est: 50, over:0.3, under:0.9 - 0.5478734029604564
depth: 1, est: 50, over:0.4, under:0.4 - 0.5334002744905819
depth: 1, est: 50, over:0.4, under:0.5 - 0.5562832945751809
depth: 1, est: 50, over:0.4, under:0.6 - 0.5701456921257129
depth: 1, est: 50, over:0.4, under:0.7 - 0.5673617876529142
depth: 1, est: 50, over:0.4, under:0.8 - 0.558496604498236
depth: 1, est: 50, over:0.4, under:0.9 - 0.5513204516488126
depth: 1, est: 50, over:0.5, under:0.5 - 0.5546879091091823
depth: 1, est: 50, over:0.5, under:0.6 - 0.5697135902120563
depth: 1, est: 50, over:0.5, under:0.7 - 0.5705755710934253
depth: 1, est: 50, over:0.5, under:0.8 - 0.5611749397095664
depth: 1, est: 50, over:0.5, under:0.9 - 0.5517375292298268
depth: 1, est: 50, over:0.6, under:0.6 - 0.5725917992767229
depth: 1, est: 50, over:0.6, under:0.7 - 0.5691962348490682
depth: 1, est: 50, over:0.6, under:0.8 - 0.5618651162230455
depth: 1, est: 50, over:0.6, under:0.9 - 0.5534415036037088
depth: 1, est: 50, over:0.7, under:0.7 - 0.5696622700011706
depth: 1, est: 50, over:0.7, under:0.8 - 0.560316398304727
depth: 1, est: 50, over:0.7, under:0.9 - 0.5520488262315487
depth: 1, est: 50, over:0.8, under:0.8 - 0.560708116773888
depth: 1, est: 50, over:0.8, under:0.9 - 0.5517375292298268
depth: 1, est: 50, over:0.9, under:0.9 - 0.5517822680187833
depth: 1, est: 100, over:0.2, under:0.2 - 0.48860034826989
depth: 1, est: 100, over:0.2, under:0.3 - 0.514588417636303
depth: 1, est: 100, over:0.2, under:0.4 - 0.5340303266579767
depth: 1, est: 100, over:0.2, under:0.5 - 0.560000726834715
depth: 1, est: 100, over:0.2, under:0.6 - 0.572621447245423
depth: 1, est: 100, over:0.2, under:0.7 - 0.5716706305530328
depth: 1, est: 100, over:0.2, under:0.8 - 0.5633291890293155
depth: 1, est: 100, over:0.2, under:0.9 - 0.5528908866765514
depth: 1, est: 100, over:0.3, under:0.3 - 0.5160211520151654
depth: 1, est: 100, over:0.3, under:0.4 - 0.5359838801868629
depth: 1, est: 100, over:0.3, under:0.5 - 0.5645178226283154

In [ ]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

spis = []
sampl = [0.3, 0.4, 0.5, 0.6, 0.7 , 0.8, 0.9, 1]

depth_max = [1, 2, 3, 5]

n_estim = [30, 50, 100, 150]



for depth1 in depth_max:
  for e1 in n_estim:
    for i1 in sampl:
      for i in sampl:

        if i1 > i:
          continue

        f1_full = []

        for train_idx, val_idx in cv.split(train_x, train_y):

          X_train_fold = train_x[train_idx]
          X_val_fold = train_x[val_idx]

          y_train_fold = train_y[train_idx]
          y_val_fold = train_y[val_idx]

          over = RandomOverSampler(random_state = 42, sampling_strategy=i1)

          train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

          tl = RandomUnderSampler(sampling_strategy = i)
          train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

          model = xgb.XGBClassifier(n_estimators = e1, max_depth = depth1, tree_method = 'hist')

          model.fit(train_x_over, train_y_over)

          res = model.predict(X_val_fold)

          ocinka = f1_score(y_val_fold, res, average='macro')

          f1_full.append(ocinka)



        res_ocinka = np.mean(f1_full)

        print(f'depth: {depth1}, est: {e1}, over:{i1}, under:{i} - {res_ocinka}')

        spis.append(res_ocinka)


spis_copy = spis.copy()

for i in range(10):
    best_idx = np.argmax(spis_copy)
    print(f"{i+1}. f1 = {spis_copy[best_idx]:.4f}")
    spis_copy[best_idx] = -1

depth: 1, est: 2, over:0.2, under:0.2 - 0.4701515594859492
depth: 1, est: 2, over:0.2, under:0.3 - 0.4701515594859492
depth: 1, est: 2, over:0.2, under:0.4 - 0.4701515594859492
depth: 1, est: 2, over:0.2, under:0.5 - 0.4701515594859492
depth: 1, est: 2, over:0.2, under:0.6 - 0.4701515594859492
depth: 1, est: 2, over:0.2, under:0.7 - 0.5415745453338405
depth: 1, est: 2, over:0.2, under:0.8 - 0.5660850488377625
depth: 1, est: 2, over:0.2, under:0.9 - 0.5660850488377625
depth: 1, est: 2, over:0.3, under:0.3 - 0.4701515594859492
depth: 1, est: 2, over:0.3, under:0.4 - 0.4701515594859492
depth: 1, est: 2, over:0.3, under:0.5 - 0.4701515594859492
depth: 1, est: 2, over:0.3, under:0.6 - 0.4701515594859492
depth: 1, est: 2, over:0.3, under:0.7 - 0.5161227075566532
depth: 1, est: 2, over:0.3, under:0.8 - 0.5660850488377625
depth: 1, est: 2, over:0.3, under:0.9 - 0.5660850488377625
depth: 1, est: 2, over:0.4, under:0.4 - 0.4701515594859492
depth: 1, est: 2, over:0.4, under:0.5 - 0.4701515594859492
depth: 1, est: 2, over:0.4, under:0.6 - 0.4701515594859492
depth: 1, est: 2, over:0.4, under:0.7 - 0.4701515594859492
depth: 1, est: 2, over:0.4, under:0.8 - 0.5660850488377625
depth: 1, est: 2, over:0.4, under:0.9 - 0.5660850488377625
depth: 1, est: 2, over:0.5, under:0.5 - 0.4701515594859492
depth: 1, est: 2, over:0.5, under:0.6 - 0.4701515594859492
depth: 1, est: 2, over:0.5, under:0.7 - 0.4701515594859492
depth: 1, est: 2, over:0.5, under:0.8 - 0.5660850488377625
depth: 1, est: 2, over:0.5, under:0.9 - 0.5660850488377625
depth: 1, est: 2, over:0.6, under:0.6 - 0.4701515594859492
depth: 1, est: 2, over:0.6, under:0.7 - 0.5161227075566532
depth: 1, est: 2, over:0.6, under:0.8 - 0.5660850488377625
depth: 1, est: 2, over:0.6, under:0.9 - 0.5660850488377625
depth: 1, est: 2, over:0.7, under:0.7 - 0.4930896756477039
depth: 1, est: 2, over:0.7, under:0.8 - 0.5660850488377625
depth: 1, est: 2, over:0.7, under:0.9 - 0.5660850488377625
depth: 1, est: 2, over:0.8, under:0.8 - 0.5660850488377625
depth: 1, est: 2, over:0.8, under:0.9 - 0.5660850488377625
depth: 1, est: 2, over:0.9, under:0.9 - 0.5660850488377625
depth: 1, est: 3, over:0.2, under:0.2 - 0.4701515594859492
depth: 1, est: 3, over:0.2, under:0.3 - 0.4701515594859492
depth: 1, est: 3, over:0.2, under:0.4 - 0.4701515594859492
depth: 1, est: 3, over:0.2, under:0.5 - 0.4701515594859492
depth: 1, est: 3, over:0.2, under:0.6 - 0.4931230173107909
depth: 1, est: 3, over:0.2, under:0.7 - 0.562369905479255
depth: 1, est: 3, over:0.2, under:0.8 - 0.5660850488377625
depth: 1, est: 3, over:0.2, under:0.9 - 0.5528357082638702
depth: 1, est: 3, over:0.3, under:0.3 - 0.4701515594859492
depth: 1, est: 3, over:0.3, under:0.4 - 0.4701515594859492
depth: 1, est: 3, over:0.3, under:0.5 - 0.4701515594859492
depth: 1, est: 3, over:0.3, under:0.6 - 0.5133159529689723
depth: 1, est: 3, over:0.3, under:0.7 - 0.5619901431943601
depth: 1, est: 3, over:0.3, under:0.8 - 0.5660850488377625
depth: 1, est: 3, over:0.3, under:0.9 - 0.550714622285196
depth: 1, est: 3, over:0.4, under:0.4 - 0.4701515594859492
depth: 1, est: 3, over:0.4, under:0.5 - 0.4701515594859492
depth: 1, est: 3, over:0.4, under:0.6 - 0.5133159529689723
depth: 1, est: 3, over:0.4, under:0.7 - 0.5587954856085381
depth: 1, est: 3, over:0.4, under:0.8 - 0.5660850488377625
depth: 1, est: 3, over:0.4, under:0.9 - 0.5660850488377625
depth: 1, est: 3, over:0.5, under:0.5 - 0.4701515594859492
depth: 1, est: 3, over:0.5, under:0.6 - 0.5085067696920935
depth: 1, est: 3, over:0.5, under:0.7 - 0.5559088844287376
depth: 1, est: 3, over:0.5, under:0.8 - 0.5660850488377625
depth: 1, est: 3, over:0.5, under:0.9 - 0.5338816014109193
depth: 1, est: 3, over:0.6, under:0.6 - 0.5085067696920935
depth: 1, est: 3, over:0.6, under:0.7 - 0.5559088844287376
depth: 1, est: 3, over:0.6, under:0.8 - 0.5660850488377625
depth: 1, est: 3, over:0.6, under:0.9 - 0.5481204857200396
depth: 1, est: 3, over:0.7, under:0.7 - 0.5559088844287376
depth: 1, est: 3, over:0.7, under:0.8 - 0.5660850488377625
depth: 1, est: 3, over:0.7, under:0.9 - 0.5445368054196553
depth: 1, est: 3, over:0.8, under:0.8 - 0.5660850488377625
depth: 1, est: 3, over:0.8, under:0.9 - 0.5613698262939318
depth: 1, est: 3, over:0.9, under:0.9 - 0.5613698262939318
depth: 1, est: 5, over:0.2, under:0.2 - 0.4701515594859492
depth: 1, est: 5, over:0.2, under:0.3 - 0.4701515594859492
depth: 1, est: 5, over:0.2, under:0.4 - 0.4701515594859492
depth: 1, est: 5, over:0.2, under:0.5 - 0.5087045889996635
depth: 1, est: 5, over:0.2, under:0.6 - 0.5395253268934286
depth: 1, est: 5, over:0.2, under:0.7 - 0.566077143234508
depth: 1, est: 5, over:0.2, under:0.8 - 0.5660850488377625
depth: 1, est: 5, over:0.2, under:0.9 - 0.5510636069501555
depth: 1, est: 5, over:0.3, under:0.3 - 0.4701515594859492
depth: 1, est: 5, over:0.3, under:0.4 - 0.4701515594859492
depth: 1, est: 5, over:0.3, under:0.5 - 0.5068646861845101
depth: 1, est: 5, over:0.3, under:0.6 - 0.5366122631797491
depth: 1, est: 5, over:0.3, under:0.7 - 0.5659136156554289
depth: 1, est: 5, over:0.3, under:0.8 - 0.5660850488377625
depth: 1, est: 5, over:0.3, under:0.9 - 0.553263866134692
depth: 1, est: 5, over:0.4, under:0.4 - 0.4701515594859492
depth: 1, est: 5, over:0.4, under:0.5 - 0.5123641294063637
depth: 1, est: 5, over:0.4, under:0.6 - 0.5528366428843532
depth: 1, est: 5, over:0.4, under:0.7 - 0.566269594101381
depth: 1, est: 5, over:0.4, under:0.8 - 0.5660850488377625
depth: 1, est: 5, over:0.4, under:0.9 - 0.5510636069501555
depth: 1, est: 5, over:0.5, under:0.5 - 0.5123641294063637
depth: 1, est: 5, over:0.5, under:0.6 - 0.5480274596074745
depth: 1, est: 5, over:0.5, under:0.7 - 0.5654197121016722
depth: 1, est: 5, over:0.5, under:0.8 - 0.5660850488377625
depth: 1, est: 5, over:0.5, under:0.9 - 0.5510636069501555
depth: 1, est: 5, over:0.6, under:0.6 - 0.5480274596074745
depth: 1, est: 5, over:0.6, under:0.7 - 0.5654197121016722
depth: 1, est: 5, over:0.6, under:0.8 - 0.5660850488377625
depth: 1, est: 5, over:0.6, under:0.9 - 0.555778829493986
depth: 1, est: 5, over:0.7, under:0.7 - 0.5654197121016722
depth: 1, est: 5, over:0.7, under:0.8 - 0.5660850488377625
depth: 1, est: 5, over:0.7, under:0.9 - 0.5510636069501555
depth: 1, est: 5, over:0.8, under:0.8 - 0.5660850488377625
depth: 1, est: 5, over:0.8, under:0.9 - 0.5510636069501555
depth: 1, est: 5, over:0.9, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.2, under:0.2 - 0.4701515594859492
depth: 1, est: 7, over:0.2, under:0.3 - 0.4715969956878462
depth: 1, est: 7, over:0.2, under:0.4 - 0.5025138787516912
depth: 1, est: 7, over:0.2, under:0.5 - 0.54097037207543
depth: 1, est: 7, over:0.2, under:0.6 - 0.561700172277065
depth: 1, est: 7, over:0.2, under:0.7 - 0.5668577345242449
depth: 1, est: 7, over:0.2, under:0.8 - 0.5664118083523139
depth: 1, est: 7, over:0.2, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.3, under:0.3 - 0.4715969956878462
depth: 1, est: 7, over:0.3, under:0.4 - 0.4886552026111454
depth: 1, est: 7, over:0.3, under:0.5 - 0.5368278495436634
depth: 1, est: 7, over:0.3, under:0.6 - 0.557941670376445
depth: 1, est: 7, over:0.3, under:0.7 - 0.5661441127512734
depth: 1, est: 7, over:0.3, under:0.8 - 0.5664118083523139
depth: 1, est: 7, over:0.3, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.4, under:0.4 - 0.4964333799302207
depth: 1, est: 7, over:0.4, under:0.5 - 0.5388779945766752
depth: 1, est: 7, over:0.4, under:0.6 - 0.5569588728140289
depth: 1, est: 7, over:0.4, under:0.7 - 0.565210299278796
depth: 1, est: 7, over:0.4, under:0.8 - 0.5620191339181204
depth: 1, est: 7, over:0.4, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.5, under:0.5 - 0.5368278495436634
depth: 1, est: 7, over:0.5, under:0.6 - 0.5589348458686767
depth: 1, est: 7, over:0.5, under:0.7 - 0.566007852524536
depth: 1, est: 7, over:0.5, under:0.8 - 0.5664118083523139
depth: 1, est: 7, over:0.5, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.6, under:0.6 - 0.5579095656124191
depth: 1, est: 7, over:0.6, under:0.7 - 0.566007852524536
depth: 1, est: 7, over:0.6, under:0.8 - 0.5664118083523139
depth: 1, est: 7, over:0.6, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.7, under:0.7 - 0.566007852524536
depth: 1, est: 7, over:0.7, under:0.8 - 0.5664118083523139
depth: 1, est: 7, over:0.7, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.8, under:0.8 - 0.5664118083523139
depth: 1, est: 7, over:0.8, under:0.9 - 0.5510636069501555
depth: 1, est: 7, over:0.9, under:0.9 - 0.5510636069501555
depth: 1, est: 10, over:0.2, under:0.2 - 0.4701515594859492
depth: 1, est: 10, over:0.2, under:0.3 - 0.476488329405537
depth: 1, est: 10, over:0.2, under:0.4 - 0.5108299047317529
depth: 1, est: 10, over:0.2, under:0.5 - 0.5420865852611019
depth: 1, est: 10, over:0.2, under:0.6 - 0.5615757154908341
depth: 1, est: 10, over:0.2, under:0.7 - 0.5664445476397879
depth: 1, est: 10, over:0.2, under:0.8 - 0.5638029386940743
depth: 1, est: 10, over:0.2, under:0.9 - 0.5496646240952753
depth: 1, est: 10, over:0.3, under:0.3 - 0.4721094395304357
depth: 1, est: 10, over:0.3, under:0.4 - 0.5159132826417258
depth: 1, est: 10, over:0.3, under:0.5 - 0.5493904705609091
depth: 1, est: 10, over:0.3, under:0.6 - 0.5603328926028048
depth: 1, est: 10, over:0.3, under:0.7 - 0.5674617813438751
depth: 1, est: 10, over:0.3, under:0.8 - 0.5665180860960863
depth: 1, est: 10, over:0.3, under:0.9 - 0.5508971351046469
depth: 1, est: 10, over:0.4, under:0.4 - 0.5181974083113721
depth: 1, est: 10, over:0.4, under:0.5 - 0.5467268098125959
depth: 1, est: 10, over:0.4, under:0.6 - 0.5618309340298269
depth: 1, est: 10, over:0.4, under:0.7 - 0.5674932314136213
depth: 1, est: 10, over:0.4, under:0.8 - 0.5662539772405003
depth: 1, est: 10, over:0.4, under:0.9 - 0.5497375896012967
depth: 1, est: 10, over:0.5, under:0.5 - 0.5426369214301612
depth: 1, est: 10, over:0.5, under:0.6 - 0.5627062588417691
depth: 1, est: 10, over:0.5, under:0.7 - 0.5665717100688892
depth: 1, est: 10, over:0.5, under:0.8 - 0.5640782413767537
depth: 1, est: 10, over:0.5, under:0.9 - 0.5497375896012967
depth: 1, est: 10, over:0.6, under:0.6 - 0.5601294402704977
depth: 1, est: 10, over:0.6, under:0.7 - 0.5680465560543608
depth: 1, est: 10, over:0.6, under:0.8 - 0.5632590192556698
depth: 1, est: 10, over:0.6, under:0.9 - 0.549051931784231
depth: 1, est: 10, over:0.7, under:0.7 - 0.5679304747054965
depth: 1, est: 10, over:0.7, under:0.8 - 0.560268956039524
depth: 1, est: 10, over:0.7, under:0.9 - 0.5495716686405999
depth: 1, est: 10, over:0.8, under:0.8 - 0.5661189940821202
depth: 1, est: 10, over:0.8, under:0.9 - 0.5495670182949274
depth: 1, est: 10, over:0.9, under:0.9 - 0.5495716686405999
depth: 1, est: 15, over:0.2, under:0.2 - 0.47252817387531887
depth: 1, est: 15, over:0.2, under:0.3 - 0.4935845653294266
depth: 1, est: 15, over:0.2, under:0.4 - 0.5313428330385862
depth: 1, est: 15, over:0.2, under:0.5 - 0.55005583213958
depth: 1, est: 15, over:0.2, under:0.6 - 0.5621986476700512
depth: 1, est: 15, over:0.2, under:0.7 - 0.5690007568656912
depth: 1, est: 15, over:0.2, under:0.8 - 0.5596403114023181
depth: 1, est: 15, over:0.2, under:0.9 - 0.5493980112596186
depth: 1, est: 15, over:0.3, under:0.3 - 0.5012396327027226
depth: 1, est: 15, over:0.3, under:0.4 - 0.5309454307432864
depth: 1, est: 15, over:0.3, under:0.5 - 0.5493582968497293
depth: 1, est: 15, over:0.3, under:0.6 - 0.5632774194658672
depth: 1, est: 15, over:0.3, under:0.7 - 0.5684981955624064
depth: 1, est: 15, over:0.3, under:0.8 - 0.557198214093164
depth: 1, est: 15, over:0.3, under:0.9 - 0.5488459987744329
depth: 1, est: 15, over:0.4, under:0.4 - 0.5308988886378714
depth: 1, est: 15, over:0.4, under:0.5 - 0.5496833026195473
depth: 1, est: 15, over:0.4, under:0.6 - 0.56582844247186
depth: 1, est: 15, over:0.4, under:0.7 - 0.566967046818263
depth: 1, est: 15, over:0.4, under:0.8 - 0.5553257993247614
depth: 1, est: 15, over:0.4, under:0.9 - 0.5487587604764562
depth: 1, est: 15, over:0.5, under:0.5 - 0.5484479881748392
depth: 1, est: 15, over:0.5, under:0.6 - 0.5654470925269796
depth: 1, est: 15, over:0.5, under:0.7 - 0.567708093361685
depth: 1, est: 15, over:0.5, under:0.8 - 0.5557235674991619
depth: 1, est: 15, over:0.5, under:0.9 - 0.5486887301650079
depth: 1, est: 15, over:0.6, under:0.6 - 0.565970973356809
depth: 1, est: 15, over:0.6, under:0.7 - 0.5681007583218878
depth: 1, est: 15, over:0.6, under:0.8 - 0.5588650430755042
depth: 1, est: 15, over:0.6, under:0.9 - 0.5498060886574825
depth: 1, est: 15, over:0.7, under:0.7 - 0.5676056950492607
depth: 1, est: 15, over:0.7, under:0.8 - 0.5570469538351742
depth: 1, est: 15, over:0.7, under:0.9 - 0.5486114390964599
depth: 1, est: 15, over:0.8, under:0.8 - 0.5565064783449436
depth: 1, est: 15, over:0.8, under:0.9 - 0.5485518476299249
depth: 1, est: 15, over:0.9, under:0.9 - 0.5487675031268214
depth: 1, est: 20, over:0.2, under:0.2 - 0.47501141449827167
depth: 1, est: 20, over:0.2, under:0.3 - 0.5025441787018284
depth: 1, est: 20, over:0.2, under:0.4 - 0.5343302054213624
depth: 1, est: 20, over:0.2, under:0.5 - 0.5526651301450098
depth: 1, est: 20, over:0.2, under:0.6 - 0.5659230929514749
depth: 1, est: 20, over:0.2, under:0.7 - 0.5683282143510502
depth: 1, est: 20, over:0.2, under:0.8 - 0.55821521966639
depth: 1, est: 20, over:0.2, under:0.9 - 0.5485276907678905
depth: 1, est: 20, over:0.3, under:0.3 - 0.5025521356647807
depth: 1, est: 20, over:0.3, under:0.4 - 0.5290913006660818
depth: 1, est: 20, over:0.3, under:0.5 - 0.5495077643290527
depth: 1, est: 20, over:0.3, under:0.6 - 0.5660575509302115
depth: 1, est: 20, over:0.3, under:0.7 - 0.5683685940747074
depth: 1, est: 20, over:0.3, under:0.8 - 0.5596075563154695
depth: 1, est: 20, over:0.3, under:0.9 - 0.5484163927974965
depth: 1, est: 20, over:0.4, under:0.4 - 0.5299176223346885
depth: 1, est: 20, over:0.4, under:0.5 - 0.5487812025773418
depth: 1, est: 20, over:0.4, under:0.6 - 0.5656124181179764
depth: 1, est: 20, over:0.4, under:0.7 - 0.5681495207171559
depth: 1, est: 20, over:0.4, under:0.8 - 0.5565599240510437
depth: 1, est: 20, over:0.4, under:0.9 - 0.5488549429433338
depth: 1, est: 20, over:0.5, under:0.5 - 0.5487044261583005
depth: 1, est: 20, over:0.5, under:0.6 - 0.5656999697242564
depth: 1, est: 20, over:0.5, under:0.7 - 0.5683647675875744
depth: 1, est: 20, over:0.5, under:0.8 - 0.5572539255641236
depth: 1, est: 20, over:0.5, under:0.9 - 0.5489568489199388
depth: 1, est: 20, over:0.6, under:0.6 - 0.5662881664160924
depth: 1, est: 20, over:0.6, under:0.7 - 0.5690422945455721
depth: 1, est: 20, over:0.6, under:0.8 - 0.5571298941629106
depth: 1, est: 20, over:0.6, under:0.9 - 0.5489164507620186
depth: 1, est: 20, over:0.7, under:0.7 - 0.5685870459176969
depth: 1, est: 20, over:0.7, under:0.8 - 0.5570957129558395
depth: 1, est: 20, over:0.7, under:0.9 - 0.5488045734150535
depth: 1, est: 20, over:0.8, under:0.8 - 0.5569401820389903
depth: 1, est: 20, over:0.8, under:0.9 - 0.5490332743997407
depth: 1, est: 20, over:0.9, under:0.9 - 0.5498718749331704
depth: 1, est: 30, over:0.2, under:0.2 - 0.4772002455107128
depth: 1, est: 30, over:0.2, under:0.3 - 0.508057066681042
depth: 1, est: 30, over:0.2, under:0.4 - 0.5349749430915611
depth: 1, est: 30, over:0.2, under:0.5 - 0.5548300080178047
depth: 1, est: 30, over:0.2, under:0.6 - 0.5667897693640731
depth: 1, est: 30, over:0.2, under:0.7 - 0.5711961294710965
depth: 1, est: 30, over:0.2, under:0.8 - 0.5601382945897911
depth: 1, est: 30, over:0.2, under:0.9 - 0.5499850606738
depth: 1, est: 30, over:0.3, under:0.3 - 0.5073663537350968
depth: 1, est: 30, over:0.3, under:0.4 - 0.5329844230174895
depth: 1, est: 30, over:0.3, under:0.5 - 0.5534918898152826
depth: 1, est: 30, over:0.3, under:0.6 - 0.5688388611748727
depth: 1, est: 30, over:0.3, under:0.7 - 0.5715623680738602
depth: 1, est: 30, over:0.3, under:0.8 - 0.5600767866783639
depth: 1, est: 30, over:0.3, under:0.9 - 0.5523905085882675
depth: 1, est: 30, over:0.4, under:0.4 - 0.5348866406993746
depth: 1, est: 30, over:0.4, under:0.5 - 0.5516247473611169
depth: 1, est: 30, over:0.4, under:0.6 - 0.5689819182470319
depth: 1, est: 30, over:0.4, under:0.7 - 0.5722245178000165
depth: 1, est: 30, over:0.4, under:0.8 - 0.5596681467756308
depth: 1, est: 30, over:0.4, under:0.9 - 0.5516566862672625
depth: 1, est: 30, over:0.5, under:0.5 - 0.5523983405136039
depth: 1, est: 30, over:0.5, under:0.6 - 0.5678343012250685
depth: 1, est: 30, over:0.5, under:0.7 - 0.5730161684948807
depth: 1, est: 30, over:0.5, under:0.8 - 0.5608186606997395
depth: 1, est: 30, over:0.5, under:0.9 - 0.5504361613746958
depth: 1, est: 30, over:0.6, under:0.6 - 0.5693397978064881
depth: 1, est: 30, over:0.6, under:0.7 - 0.5733519460948778
depth: 1, est: 30, over:0.6, under:0.8 - 0.5611746981355789
depth: 1, est: 30, over:0.6, under:0.9 - 0.5507515050379607
depth: 1, est: 30, over:0.7, under:0.7 - 0.5714044300332662
depth: 1, est: 30, over:0.7, under:0.8 - 0.5595663339289011
depth: 1, est: 30, over:0.7, under:0.9 - 0.5502642474509369
depth: 1, est: 30, over:0.8, under:0.8 - 0.5601713525222477
depth: 1, est: 30, over:0.8, under:0.9 - 0.5510447809073615
depth: 1, est: 30, over:0.9, under:0.9 - 0.5515663574507628
depth: 1, est: 50, over:0.2, under:0.2 - 0.4825209337830859
depth: 1, est: 50, over:0.2, under:0.3 - 0.5112549721853407
depth: 1, est: 50, over:0.2, under:0.4 - 0.537256143028254
depth: 1, est: 50, over:0.2, under:0.5 - 0.5582190449780126
depth: 1, est: 50, over:0.2, under:0.6 - 0.5734792996721099
depth: 1, est: 50, over:0.2, under:0.7 - 0.5735601305484375
depth: 1, est: 50, over:0.2, under:0.8 - 0.5659432845791932
depth: 1, est: 50, over:0.2, under:0.9 - 0.5504352999367552
depth: 1, est: 50, over:0.3, under:0.3 - 0.5118787106990121
depth: 1, est: 50, over:0.3, under:0.4 - 0.5368474948517296
depth: 1, est: 50, over:0.3, under:0.5 - 0.55902041576602
depth: 1, est: 50, over:0.3, under:0.6 - 0.5711870283360402
depth: 1, est: 50, over:0.3, under:0.7 - 0.57339892589202
depth: 1, est: 50, over:0.3, under:0.8 - 0.565921779555986
depth: 1, est: 50, over:0.3, under:0.9 - 0.5537288323567008
depth: 1, est: 50, over:0.4, under:0.4 - 0.5379988843123831
depth: 1, est: 50, over:0.4, under:0.5 - 0.5571704091157953
depth: 1, est: 50, over:0.4, under:0.6 - 0.5723626768799507
depth: 1, est: 50, over:0.4, under:0.7 - 0.5731386521242892
depth: 1, est: 50, over:0.4, under:0.8 - 0.5648611938230059
depth: 1, est: 50, over:0.4, under:0.9 - 0.5533638995453638
depth: 1, est: 50, over:0.5, under:0.5 - 0.5572227096893969
depth: 1, est: 50, over:0.5, under:0.6 - 0.5734914954884209
depth: 1, est: 50, over:0.5, under:0.7 - 0.5739403689477369
depth: 1, est: 50, over:0.5, under:0.8 - 0.5659988263408513
depth: 1, est: 50, over:0.5, under:0.9 - 0.5550105303064825
depth: 1, est: 50, over:0.6, under:0.6 - 0.5730967651823516
depth: 1, est: 50, over:0.6, under:0.7 - 0.5731158582244077
depth: 1, est: 50, over:0.6, under:0.8 - 0.5659038670797729
depth: 1, est: 50, over:0.6, under:0.9 - 0.5532436744358576
depth: 1, est: 50, over:0.7, under:0.7 - 0.574304642006353
depth: 1, est: 50, over:0.7, under:0.8 - 0.5659142030101625
depth: 1, est: 50, over:0.7, under:0.9 - 0.5534389402835326
depth: 1, est: 50, over:0.8, under:0.8 - 0.5651422565966184
depth: 1, est: 50, over:0.8, under:0.9 - 0.5533849138842767
depth: 1, est: 50, over:0.9, under:0.9 - 0.5535987847203689
depth: 1, est: 100, over:0.2, under:0.2 - 0.4871454020488627
depth: 1, est: 100, over:0.2, under:0.3 - 0.5174103085896831
depth: 1, est: 100, over:0.2, under:0.4 - 0.539429456412494
depth: 1, est: 100, over:0.2, under:0.5 - 0.5649507898101153
depth: 1, est: 100, over:0.2, under:0.6 - 0.577246537163288
depth: 1, est: 100, over:0.2, under:0.7 - 0.5766067589431273
depth: 1, est: 100, over:0.2, under:0.8 - 0.5679607221129862
depth: 1, est: 100, over:0.2, under:0.9 - 0.5559600689637831
depth: 1, est: 100, over:0.3, under:0.3 - 0.5158544919841735
depth: 1, est: 100, over:0.3, under:0.4 - 0.5413104707978147
depth: 1, est: 100, over:0.3, under:0.5 - 0.5640908458274777
depth: 1, est: 100, over:0.3, under:0.6 - 0.5771177134510187

In [ ]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

spis = []
sampl = [0.3, 0.4, 0.5, 0.6, 0.7 , 0.8, 0.9, 1]

depth_max = [1, 2, 3, 5]

n_estim = [20, 30, 50, 100, 150]



for depth1 in depth_max:
  for e1 in n_estim:
    for i1 in sampl:
      for i in sampl:

        if i1 > i:
          continue

        f1_full = []

        for train_idx, val_idx in cv.split(train_x, train_y):

          X_train_fold = train_x[train_idx]
          X_val_fold = train_x[val_idx]

          y_train_fold = train_y[train_idx]
          y_val_fold = train_y[val_idx]

          over = RandomOverSampler(random_state = 42, sampling_strategy=i1)

          train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

          tl = RandomUnderSampler(sampling_strategy = i)
          train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

          model = xgb.XGBClassifier(n_estimators = e1, max_depth = depth1, tree_method = 'hist')

          model.fit(train_x_over, train_y_over)

          res = model.predict(X_val_fold)

          ocinka = f1_score(y_val_fold, res, average='macro')

          f1_full.append(ocinka)



        res_ocinka = np.mean(f1_full)

        print(f'depth: {depth1}, est: {e1}, over:{i1}, under:{i} - {res_ocinka}')

        spis.append(res_ocinka)


spis_copy = spis.copy()

for i in range(10):
    best_idx = np.argmax(spis_copy)
    print(f"{i+1}. f1 = {spis_copy[best_idx]:.4f}")
    spis_copy[best_idx] = -1

depth: 1, est: 20, over:0.3, under:0.3 - 0.5040305527369671
depth: 1, est: 20, over:0.3, under:0.4 - 0.5313303480049106
depth: 1, est: 20, over:0.3, under:0.5 - 0.5509044918877612
depth: 1, est: 20, over:0.3, under:0.6 - 0.5667744055476945
depth: 1, est: 20, over:0.3, under:0.7 - 0.5688783891246627
depth: 1, est: 20, over:0.3, under:0.8 - 0.5616807776406358
depth: 1, est: 20, over:0.3, under:0.9 - 0.549513470065798
depth: 1, est: 20, over:0.3, under:1 - 0.5303889622671064
depth: 1, est: 20, over:0.4, under:0.4 - 0.5324315894068808
depth: 1, est: 20, over:0.4, under:0.5 - 0.5514553642154372
depth: 1, est: 20, over:0.4, under:0.6 - 0.5675585152530509
depth: 1, est: 20, over:0.4, under:0.7 - 0.5688786920110824
depth: 1, est: 20, over:0.4, under:0.8 - 0.5608722403263876
depth: 1, est: 20, over:0.4, under:0.9 - 0.5484320567008731
depth: 1, est: 20, over:0.4, under:1 - 0.5361906330565676
depth: 1, est: 20, over:0.5, under:0.5 - 0.5523237704657415
depth: 1, est: 20, over:0.5, under:0.6 - 0.5670537134653374
depth: 1, est: 20, over:0.5, under:0.7 - 0.5679366204209153
depth: 1, est: 20, over:0.5, under:0.8 - 0.5600509982162535
depth: 1, est: 20, over:0.5, under:0.9 - 0.5486153319365703
depth: 1, est: 20, over:0.5, under:1 - 0.5313936225737776
depth: 1, est: 20, over:0.6, under:0.6 - 0.5677827743534192
depth: 1, est: 20, over:0.6, under:0.7 - 0.5675605145909814
depth: 1, est: 20, over:0.6, under:0.8 - 0.5588925066561576
depth: 1, est: 20, over:0.6, under:0.9 - 0.5439978101184583
depth: 1, est: 20, over:0.6, under:1 - 0.5321681596573332
depth: 1, est: 20, over:0.7, under:0.7 - 0.5678674770564403
depth: 1, est: 20, over:0.7, under:0.8 - 0.559514304800609
depth: 1, est: 20, over:0.7, under:0.9 - 0.5490595785426295
depth: 1, est: 20, over:0.7, under:1 - 0.530284483154516
depth: 1, est: 20, over:0.8, under:0.8 - 0.560380707999061
depth: 1, est: 20, over:0.8, under:0.9 - 0.5498064277940616
depth: 1, est: 20, over:0.8, under:1 - 0.5318586041129507
depth: 1, est: 20, over:0.9, under:0.9 - 0.5498551920463786
depth: 1, est: 20, over:0.9, under:1 - 0.5322035769240964
depth: 1, est: 20, over:1, under:1 - 0.5300646425950029
depth: 1, est: 30, over:0.3, under:0.3 - 0.5114057499279954
depth: 1, est: 30, over:0.3, under:0.4 - 0.5396979062479209
depth: 1, est: 30, over:0.3, under:0.5 - 0.556225787701712
depth: 1, est: 30, over:0.3, under:0.6 - 0.569316352692993
depth: 1, est: 30, over:0.3, under:0.7 - 0.5718727100011821
depth: 1, est: 30, over:0.3, under:0.8 - 0.5643695447268124
depth: 1, est: 30, over:0.3, under:0.9 - 0.5517341400911369
depth: 1, est: 30, over:0.3, under:1 - 0.535538333155219
depth: 1, est: 30, over:0.4, under:0.4 - 0.5366095666695708
depth: 1, est: 30, over:0.4, under:0.5 - 0.5573725041806896
depth: 1, est: 30, over:0.4, under:0.6 - 0.5709729294256762
depth: 1, est: 30, over:0.4, under:0.7 - 0.5716486909087143
depth: 1, est: 30, over:0.4, under:0.8 - 0.5636028165752321
depth: 1, est: 30, over:0.4, under:0.9 - 0.549432492401704
depth: 1, est: 30, over:0.4, under:1 - 0.5335127023574404
depth: 1, est: 30, over:0.5, under:0.5 - 0.5566542138205024
depth: 1, est: 30, over:0.5, under:0.6 - 0.5713887033242799
depth: 1, est: 30, over:0.5, under:0.7 - 0.5721794419999391
depth: 1, est: 30, over:0.5, under:0.8 - 0.5621891739157646
depth: 1, est: 30, over:0.5, under:0.9 - 0.5491322617789827
depth: 1, est: 30, over:0.5, under:1 - 0.5304860384094234
depth: 1, est: 30, over:0.6, under:0.6 - 0.5706826174913799
depth: 1, est: 30, over:0.6, under:0.7 - 0.5727009867645674
depth: 1, est: 30, over:0.6, under:0.8 - 0.5616289061978847
depth: 1, est: 30, over:0.6, under:0.9 - 0.5490412641113701
depth: 1, est: 30, over:0.6, under:1 - 0.5348664776205584
depth: 1, est: 30, over:0.7, under:0.7 - 0.5713832845338477
depth: 1, est: 30, over:0.7, under:0.8 - 0.5635067058377307
depth: 1, est: 30, over:0.7, under:0.9 - 0.549145537999957
depth: 1, est: 30, over:0.7, under:1 - 0.530293849708197
depth: 1, est: 30, over:0.8, under:0.8 - 0.5630103589123621
depth: 1, est: 30, over:0.8, under:0.9 - 0.5493895392181254
depth: 1, est: 30, over:0.8, under:1 - 0.5359772401164515
depth: 1, est: 30, over:0.9, under:0.9 - 0.5493202548508099
depth: 1, est: 30, over:0.9, under:1 - 0.5296968155280408
depth: 1, est: 30, over:1, under:1 - 0.5327700096081027
depth: 1, est: 50, over:0.3, under:0.3 - 0.5154925380040679
depth: 1, est: 50, over:0.3, under:0.4 - 0.5410111369347763
depth: 1, est: 50, over:0.3, under:0.5 - 0.5615891391545744
depth: 1, est: 50, over:0.3, under:0.6 - 0.5744982227852397
depth: 1, est: 50, over:0.3, under:0.7 - 0.5743744388423354
depth: 1, est: 50, over:0.3, under:0.8 - 0.5675948085716018
depth: 1, est: 50, over:0.3, under:0.9 - 0.5540420320179138
depth: 1, est: 50, over:0.3, under:1 - 0.5327263538468302
depth: 1, est: 50, over:0.4, under:0.4 - 0.5415705280905319
depth: 1, est: 50, over:0.4, under:0.5 - 0.5622331375944255
depth: 1, est: 50, over:0.4, under:0.6 - 0.5754603857404876
depth: 1, est: 50, over:0.4, under:0.7 - 0.5742896215883778
depth: 1, est: 50, over:0.4, under:0.8 - 0.5646940544178853
depth: 1, est: 50, over:0.4, under:0.9 - 0.554066371379714
depth: 1, est: 50, over:0.4, under:1 - 0.5307058230992217
depth: 1, est: 50, over:0.5, under:0.5 - 0.5610887977585359
depth: 1, est: 50, over:0.5, under:0.6 - 0.5760579411180509
depth: 1, est: 50, over:0.5, under:0.7 - 0.573839212325965
depth: 1, est: 50, over:0.5, under:0.8 - 0.5674550382832753
depth: 1, est: 50, over:0.5, under:0.9 - 0.5520662509425106
depth: 1, est: 50, over:0.5, under:1 - 0.5318831887419051
depth: 1, est: 50, over:0.6, under:0.6 - 0.576545115792495
depth: 1, est: 50, over:0.6, under:0.7 - 0.5733843530180314
depth: 1, est: 50, over:0.6, under:0.8 - 0.5670944942699463
depth: 1, est: 50, over:0.6, under:0.9 - 0.5544210369874331
depth: 1, est: 50, over:0.6, under:1 - 0.5306868779443225
depth: 1, est: 50, over:0.7, under:0.7 - 0.5738945255345009
depth: 1, est: 50, over:0.7, under:0.8 - 0.5662656057111896
depth: 1, est: 50, over:0.7, under:0.9 - 0.5531560952392631
depth: 1, est: 50, over:0.7, under:1 - 0.5304535090682561
depth: 1, est: 50, over:0.8, under:0.8 - 0.566724640852065
depth: 1, est: 50, over:0.8, under:0.9 - 0.5528609288678575
depth: 1, est: 50, over:0.8, under:1 - 0.5310958510341827
depth: 1, est: 50, over:0.9, under:0.9 - 0.5548231142181562
depth: 1, est: 50, over:0.9, under:1 - 0.5347840228090888
depth: 1, est: 50, over:1, under:1 - 0.5317971215324253
depth: 1, est: 100, over:0.3, under:0.3 - 0.5201314927642537
depth: 1, est: 100, over:0.3, under:0.4 - 0.5465758318521863
depth: 1, est: 100, over:0.3, under:0.5 - 0.5688835079546695
depth: 1, est: 100, over:0.3, under:0.6 - 0.5778251184935104
depth: 1, est: 100, over:0.3, under:0.7 - 0.5769904398263148
depth: 1, est: 100, over:0.3, under:0.8 - 0.5696580166706493
depth: 1, est: 100, over:0.3, under:0.9 - 0.5550584131313723
depth: 1, est: 100, over:0.3, under:1 - 0.5295489017895176
depth: 1, est: 100, over:0.4, under:0.4 - 0.5466999103871291
depth: 1, est: 100, over:0.4, under:0.5 - 0.567541244665071
depth: 1, est: 100, over:0.4, under:0.6 - 0.5783436712585593
depth: 1, est: 100, over:0.4, under:0.7 - 0.5757431227810333
depth: 1, est: 100, over:0.4, under:0.8 - 0.56933666251733
depth: 1, est: 100, over:0.4, under:0.9 - 0.5575236283324168
depth: 1, est: 100, over:0.4, under:1 - 0.530906018690986
depth: 1, est: 100, over:0.5, under:0.5 - 0.5688192717791618
depth: 1, est: 100, over:0.5, under:0.6 - 0.579485204944717
depth: 1, est: 100, over:0.5, under:0.7 - 0.5757301715349495
depth: 1, est: 100, over:0.5, under:0.8 - 0.5692198830145705
depth: 1, est: 100, over:0.5, under:0.9 - 0.5569502408193212
depth: 1, est: 100, over:0.5, under:1 - 0.5307261196639101
depth: 1, est: 100, over:0.6, under:0.6 - 0.5780667643104199
depth: 1, est: 100, over:0.6, under:0.7 - 0.57570556999146
depth: 1, est: 100, over:0.6, under:0.8 - 0.5697261022789295
depth: 1, est: 100, over:0.6, under:0.9 - 0.5561587058594568
depth: 1, est: 100, over:0.6, under:1 - 0.5324186355277003
depth: 1, est: 100, over:0.7, under:0.7 - 0.5765200761300446
depth: 1, est: 100, over:0.7, under:0.8 - 0.5688395527989583
depth: 1, est: 100, over:0.7, under:0.9 - 0.5555533872457448
depth: 1, est: 100, over:0.7, under:1 - 0.531370447494482
depth: 1, est: 100, over:0.8, under:0.8 - 0.5681703208770778
depth: 1, est: 100, over:0.8, under:0.9 - 0.555248085360307
depth: 1, est: 100, over:0.8, under:1 - 0.5303754496503305
depth: 1, est: 100, over:0.9, under:0.9 - 0.5567321948980646
depth: 1, est: 100, over:0.9, under:1 - 0.5310044858569397
depth: 1, est: 100, over:1, under:1 - 0.5305873611270541
depth: 1, est: 150, over:0.3, under:0.3 - 0.5230252796515609
depth: 1, est: 150, over:0.3, under:0.4 - 0.5501227887673534
depth: 1, est: 150, over:0.3, under:0.5 - 0.5731077708444265
depth: 1, est: 150, over:0.3, under:0.6 - 0.5781929280262299
depth: 1, est: 150, over:0.3, under:0.7 - 0.5771946293109613
depth: 1, est: 150, over:0.3, under:0.8 - 0.5701861824992718
depth: 1, est: 150, over:0.3, under:0.9 - 0.5554565124701516
depth: 1, est: 150, over:0.3, under:1 - 0.5294342451708255
depth: 1, est: 150, over:0.4, under:0.4 - 0.5497647378844512
depth: 1, est: 150, over:0.4, under:0.5 - 0.5726030504394966
depth: 1, est: 150, over:0.4, under:0.6 - 0.5790232936573915
depth: 1, est: 150, over:0.4, under:0.7 - 0.576291113069589
depth: 1, est: 150, over:0.4, under:0.8 - 0.5687500839032926
depth: 1, est: 150, over:0.4, under:0.9 - 0.5549697623246501
depth: 1, est: 150, over:0.4, under:1 - 0.5283806198495333
depth: 1, est: 150, over:0.5, under:0.5 - 0.5729257977684101
depth: 1, est: 150, over:0.5, under:0.6 - 0.5792058974565593
depth: 1, est: 150, over:0.5, under:0.7 - 0.5769591165684175
depth: 1, est: 150, over:0.5, under:0.8 - 0.5686764196930612
depth: 1, est: 150, over:0.5, under:0.9 - 0.5522140416990047
depth: 1, est: 150, over:0.5, under:1 - 0.5277357364717505
depth: 1, est: 150, over:0.6, under:0.6 - 0.5781670385313218
depth: 1, est: 150, over:0.6, under:0.7 - 0.5759692189212398
depth: 1, est: 150, over:0.6, under:0.8 - 0.5687474227525329
depth: 1, est: 150, over:0.6, under:0.9 - 0.5545753659855719
depth: 1, est: 150, over:0.6, under:1 - 0.527933702218113
depth: 1, est: 150, over:0.7, under:0.7 - 0.5763393027206476
depth: 1, est: 150, over:0.7, under:0.8 - 0.5699698696671447
depth: 1, est: 150, over:0.7, under:0.9 - 0.5535069315818549
depth: 1, est: 150, over:0.7, under:1 - 0.527934575797738
depth: 1, est: 150, over:0.8, under:0.8 - 0.569744882922418
depth: 1, est: 150, over:0.8, under:0.9 - 0.5537357480116701
depth: 1, est: 150, over:0.8, under:1 - 0.5290905731409692
depth: 1, est: 150, over:0.9, under:0.9 - 0.5543348200038493
depth: 1, est: 150, over:0.9, under:1 - 0.529813036760314
depth: 1, est: 150, over:1, under:1 - 0.5288203587396537
depth: 2, est: 20, over:0.3, under:0.3 - 0.5097071762517613
depth: 2, est: 20, over:0.3, under:0.4 - 0.5367289432078745
depth: 2, est: 20, over:0.3, under:0.5 - 0.5620000981127589
depth: 2, est: 20, over:0.3, under:0.6 - 0.5790836241469417
depth: 2, est: 20, over:0.3, under:0.7 - 0.5765075593442694
depth: 2, est: 20, over:0.3, under:0.8 - 0.568845543139755
depth: 2, est: 20, over:0.3, under:0.9 - 0.5482319818316255
depth: 2, est: 20, over:0.3, under:1 - 0.5162605967135812
depth: 2, est: 20, over:0.4, under:0.4 - 0.5390946963568937
depth: 2, est: 20, over:0.4, under:0.5 - 0.5645763160257526
depth: 2, est: 20, over:0.4, under:0.6 - 0.5788245052509683
depth: 2, est: 20, over:0.4, under:0.7 - 0.5761731491387351
depth: 2, est: 20, over:0.4, under:0.8 - 0.5663082261662997
depth: 2, est: 20, over:0.4, under:0.9 - 0.5478196451517612
depth: 2, est: 20, over:0.4, under:1 - 0.5151167402515059
depth: 2, est: 20, over:0.5, under:0.5 - 0.5663164673166023
depth: 2, est: 20, over:0.5, under:0.6 - 0.5766778118627014
depth: 2, est: 20, over:0.5, under:0.7 - 0.5754677490898087
depth: 2, est: 20, over:0.5, under:0.8 - 0.5667680143368988
depth: 2, est: 20, over:0.5, under:0.9 - 0.5499878395384149
depth: 2, est: 20, over:0.5, under:1 - 0.5153413206104849
depth: 2, est: 20, over:0.6, under:0.6 - 0.5783167311038935
depth: 2, est: 20, over:0.6, under:0.7 - 0.5772296852312804
depth: 2, est: 20, over:0.6, under:0.8 - 0.5677895428942696
depth: 2, est: 20, over:0.6, under:0.9 - 0.5501372223371097
depth: 2, est: 20, over:0.6, under:1 - 0.5166122474952984
depth: 2, est: 20, over:0.7, under:0.7 - 0.5759696992553932
depth: 2, est: 20, over:0.7, under:0.8 - 0.5668940817505682
depth: 2, est: 20, over:0.7, under:0.9 - 0.5488713558325007
depth: 2, est: 20, over:0.7, under:1 - 0.5144212884443519
depth: 2, est: 20, over:0.8, under:0.8 - 0.5660627721303593
depth: 2, est: 20, over:0.8, under:0.9 - 0.5481923894090849
depth: 2, est: 20, over:0.8, under:1 - 0.5114946989799648
depth: 2, est: 20, over:0.9, under:0.9 - 0.548588805530426
depth: 2, est: 20, over:0.9, under:1 - 0.5156625768138484
depth: 2, est: 20, over:1, under:1 - 0.5134872905355836
depth: 2, est: 30, over:0.3, under:0.3 - 0.5139350351667658
depth: 2, est: 30, over:0.3, under:0.4 - 0.5442106963301234
depth: 2, est: 30, over:0.3, under:0.5 - 0.5707978613801679
depth: 2, est: 30, over:0.3, under:0.6 - 0.5805570570051944
depth: 2, est: 30, over:0.3, under:0.7 - 0.5766607753876756
depth: 2, est: 30, over:0.3, under:0.8 - 0.5673147708816197
depth: 2, est: 30, over:0.3, under:0.9 - 0.5456810861813078
depth: 2, est: 30, over:0.3, under:1 - 0.513864047243773
depth: 2, est: 30, over:0.4, under:0.4 - 0.547768589731113
depth: 2, est: 30, over:0.4, under:0.5 - 0.5708414639733611
depth: 2, est: 30, over:0.4, under:0.6 - 0.5780612905376908
depth: 2, est: 30, over:0.4, under:0.7 - 0.5747257993300621
depth: 2, est: 30, over:0.4, under:0.8 - 0.5668187593532831
depth: 2, est: 30, over:0.4, under:0.9 - 0.5450719409522721
depth: 2, est: 30, over:0.4, under:1 - 0.5143840464738929
depth: 2, est: 30, over:0.5, under:0.5 - 0.5693676924973827
depth: 2, est: 30, over:0.5, under:0.6 - 0.579364047281742
depth: 2, est: 30, over:0.5, under:0.7 - 0.5772116883679521
depth: 2, est: 30, over:0.5, under:0.8 - 0.565804876227362
depth: 2, est: 30, over:0.5, under:0.9 - 0.5459076369449837
depth: 2, est: 30, over:0.5, under:1 - 0.5145774801577486
depth: 2, est: 30, over:0.6, under:0.6 - 0.5795274929936426
depth: 2, est: 30, over:0.6, under:0.7 - 0.5770798695379274
depth: 2, est: 30, over:0.6, under:0.8 - 0.5669785987162068
depth: 2, est: 30, over:0.6, under:0.9 - 0.5479918484711944
depth: 2, est: 30, over:0.6, under:1 - 0.5166116196433038
depth: 2, est: 30, over:0.7, under:0.7 - 0.57761745254922
depth: 2, est: 30, over:0.7, under:0.8 - 0.5661388958197804
depth: 2, est: 30, over:0.7, under:0.9 - 0.5475093123392434
depth: 2, est: 30, over:0.7, under:1 - 0.5156476593693531
depth: 2, est: 30, over:0.8, under:0.8 - 0.5671281771823141
depth: 2, est: 30, over:0.8, under:0.9 - 0.5473021693942237
depth: 2, est: 30, over:0.8, under:1 - 0.5175950289700624
depth: 2, est: 30, over:0.9, under:0.9 - 0.5479510490495914
depth: 2, est: 30, over:0.9, under:1 - 0.5169255859259823
depth: 2, est: 30, over:1, under:1 - 0.5158715796205141
depth: 2, est: 50, over:0.3, under:0.3 - 0.5204230332360684
depth: 2, est: 50, over:0.3, under:0.4 - 0.551264662101083
depth: 2, est: 50, over:0.3, under:0.5 - 0.5733090567715494
depth: 2, est: 50, over:0.3, under:0.6 - 0.579692943270351
depth: 2, est: 50, over:0.3, under:0.7 - 0.575783525425317
depth: 2, est: 50, over:0.3, under:0.8 - 0.5644371954781502
depth: 2, est: 50, over:0.3, under:0.9 - 0.545429486184779
depth: 2, est: 50, over:0.3, under:1 - 0.5175526680892307
depth: 2, est: 50, over:0.4, under:0.4 - 0.5524963631270163
depth: 2, est: 50, over:0.4, under:0.5 - 0.5726995596015303
depth: 2, est: 50, over:0.4, under:0.6 - 0.581037303823197
depth: 2, est: 50, over:0.4, under:0.7 - 0.5766930225547819
depth: 2, est: 50, over:0.4, under:0.8 - 0.5642916501058726
depth: 2, est: 50, over:0.4, under:0.9 - 0.546102544715207
depth: 2, est: 50, over:0.4, under:1 - 0.5206204034842248
depth: 2, est: 50, over:0.5, under:0.5 - 0.5726586126313162
depth: 2, est: 50, over:0.5, under:0.6 - 0.5805834203443773
depth: 2, est: 50, over:0.5, under:0.7 - 0.5781042034710264
depth: 2, est: 50, over:0.5, under:0.8 - 0.5661167444388882
depth: 2, est: 50, over:0.5, under:0.9 - 0.545493704650074
depth: 2, est: 50, over:0.5, under:1 - 0.5187567246305487
depth: 2, est: 50, over:0.6, under:0.6 - 0.5801761007425712
depth: 2, est: 50, over:0.6, under:0.7 - 0.5777219717925985
depth: 2, est: 50, over:0.6, under:0.8 - 0.5653509758267752
depth: 2, est: 50, over:0.6, under:0.9 - 0.5454406348270483
depth: 2, est: 50, over:0.6, under:1 - 0.517922470450699
depth: 2, est: 50, over:0.7, under:0.7 - 0.5778356624457139
depth: 2, est: 50, over:0.7, under:0.8 - 0.566696343945579
depth: 2, est: 50, over:0.7, under:0.9 - 0.5442824348431834
depth: 2, est: 50, over:0.7, under:1 - 0.5166949103967251
depth: 2, est: 50, over:0.8, under:0.8 - 0.5651344006439343
depth: 2, est: 50, over:0.8, under:0.9 - 0.5440001449641287
depth: 2, est: 50, over:0.8, under:1 - 0.5179848294549732
depth: 2, est: 50, over:0.9, under:0.9 - 0.5443612257665793
depth: 2, est: 50, over:0.9, under:1 - 0.5183068154108378
depth: 2, est: 50, over:1, under:1 - 0.516578659783995
depth: 2, est: 100, over:0.3, under:0.3 - 0.5284488871862082
depth: 2, est: 100, over:0.3, under:0.4 - 0.5570329504349224
depth: 2, est: 100, over:0.3, under:0.5 - 0.5760139726564713
depth: 2, est: 100, over:0.3, under:0.6 - 0.5816296438419735
depth: 2, est: 100, over:0.3, under:0.7 - 0.5771240591633957
depth: 2, est: 100, over:0.3, under:0.8 - 0.5627808190469709
depth: 2, est: 100, over:0.3, under:0.9 - 0.5422511238016906
depth: 2, est: 100, over:0.3, under:1 - 0.5206364347899572
depth: 2, est: 100, over:0.4, under:0.4 - 0.5557235854157945
depth: 2, est: 100, over:0.4, under:0.5 - 0.5793869694630078
depth: 2, est: 100, over:0.4, under:0.6 - 0.5816310820352902
depth: 2, est: 100, over:0.4, under:0.7 - 0.5762562222793263
depth: 2, est: 100, over:0.4, under:0.8 - 0.5640176370899261
depth: 2, est: 100, over:0.4, under:0.9 - 0.54361780808075
depth: 2, est: 100, over:0.4, under:1 - 0.5214661738129711
depth: 2, est: 100, over:0.5, under:0.5 - 0.5761868876544325
depth: 2, est: 100, over:0.5, under:0.6 - 0.5817008230624412
depth: 2, est: 100, over:0.5, under:0.7 - 0.5779963853552929
depth: 2, est: 100, over:0.5, under:0.8 - 0.5642323651936453
depth: 2, est: 100, over:0.5, under:0.9 - 0.5428306074210161
depth: 2, est: 100, over:0.5, under:1 - 0.5207612166150724
depth: 2, est: 100, over:0.6, under:0.6 - 0.5826003027531688
depth: 2, est: 100, over:0.6, under:0.7 - 0.5767634365887259
depth: 2, est: 100, over:0.6, under:0.8 - 0.5659245749616698
depth: 2, est: 100, over:0.6, under:0.9 - 0.5441488303116516
depth: 2, est: 100, over:0.6, under:1 - 0.5207392203786149
depth: 2, est: 100, over:0.7, under:0.7 - 0.5766090671087526
depth: 2, est: 100, over:0.7, under:0.8 - 0.5639629212622947
depth: 2, est: 100, over:0.7, under:0.9 - 0.5433815530804255
depth: 2, est: 100, over:0.7, under:1 - 0.5218821088766472
depth: 2, est: 100, over:0.8, under:0.8 - 0.5653993634587293
depth: 2, est: 100, over:0.8, under:0.9 - 0.5452557441715147
depth: 2, est: 100, over:0.8, under:1 - 0.5222814187079071
depth: 2, est: 100, over:0.9, under:0.9 - 0.5432772683654497
depth: 2, est: 100, over:0.9, under:1 - 0.5210934849066594
depth: 2, est: 100, over:1, under:1 - 0.5197237277274009
depth: 2, est: 150, over:0.3, under:0.3 - 0.529309928210637
depth: 2, est: 150, over:0.3, under:0.4 - 0.5590260075309484
depth: 2, est: 150, over:0.3, under:0.5 - 0.5771881816563105
depth: 2, est: 150, over:0.3, under:0.6 - 0.5795474127098332
depth: 2, est: 150, over:0.3, under:0.7 - 0.5744925313152554
depth: 2, est: 150, over:0.3, under:0.8 - 0.5611245706361765
depth: 2, est: 150, over:0.3, under:0.9 - 0.5415558799024617
depth: 2, est: 150, over:0.3, under:1 - 0.5214639534413159
depth: 2, est: 150, over:0.4, under:0.4 - 0.559868259585071
depth: 2, est: 150, over:0.4, under:0.5 - 0.5778677097301042

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# train = pd.read_csv('train.csv')
# test = pd.read_csv('test.csv')


# train['f_10_iszero'] = (train['f_10'] == 0).astype(int)
# test['f_10_iszero'] = (test['f_10'] == 0).astype(int)

# train_y = train['target']
# train_x = train.drop(columns=['target', 'id'])
# test_x = test.drop(columns=['id'])


# num_cols = [col for col in train_x.columns if col.startswith('f_')]
# cat_cols = [col for col in train_x.columns if col.startswith('fc_')]

# columns_on_train = train_x.columns

# scaler = StandardScaler()
# train_num = scaler.fit_transform(train_x[num_cols])
# test_num = scaler.transform(test_x[num_cols])

# train_x = np.hstack([train_num, train_x[cat_cols].values])
# test_x = np.hstack([test_num, test_x[cat_cols].values])

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')


# 'f2_x_f4': 64, 'f_2^2': 32, 'f_4^2': 32, 'f_9^2': 32, 'f_10^2': 32, 'f_9_is_zero': 32, 'f_10_is_zero': 32


# features = [2, 4, 9, 10]

# additional_df = pd.DataFrame()


# for i in features:
#   additional_df[f'f_{i}^2'] = train[f'f_{i}'] * train[f'f_{i}']

# eps = 1e-6


# additional_df['f_2_div_f4'] = train['f_2'] / (train['f_4'] + eps)


# additional_df['f10_x_f2'] = train['f_10'] * train['f_2']

# additional_df['f10_x_f4'] = train['f_10'] * train['f_4']

# additional_df['f2_x_f4'] = train['f_2'] * train['f_4']



train['f10_x_f4'] = train['f_10'] * train['f_4']
test['f10_x_f4'] = test['f_10'] * test['f_4']

train['f4_x_f2'] = train['f_2'] * train['f_4']
test['f4_x_f2'] = test['f_2'] * test['f_4']


train['f10_x_f2'] = train['f_2'] * train['f_10']
test['f10_x_f2'] = test['f_2'] * test['f_10']

eps = 1e-6

train['f_2_div_f4'] = train['f_2'] / (train['f_4'] + eps)
test['f_2_div_f4'] = test['f_2'] / (test['f_4'] + eps)

train['f_new'] = train['f_4'] * train['f_10'] * train['f_2']
test['f_new'] = test['f_4'] * test['f_10'] * test['f_2']


num_cols = [col for col in train.columns if col.startswith('f_')]
cat_cols = [col for col in train.columns if col.startswith('fc_')]

train_y = train['target']
train_x = train.drop(columns=['target', 'id'])

columns_on_train = train_x.columns
test_x = test.drop(columns=['id'])

scaler = StandardScaler()
train_num = scaler.fit_transform(train_x[num_cols])
test_num = scaler.transform(test_x[num_cols])

train_x = np.hstack([train_num, train_x[cat_cols].values])
test_x  = np.hstack([test_num, test_x[cat_cols].values])

In [ ]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=4, shuffle=True)

f1_full = []
for train_idx, val_idx in cv.split(train_x, train_y):

  X_train_fold = train_x[train_idx]
  X_val_fold = train_x[val_idx]

  y_train_fold = train_y[train_idx]
  y_val_fold = train_y[val_idx]

  over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

  train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

  tl = RandomUnderSampler(sampling_strategy = 0.6, random_state=42)
  train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

  model = xgb.XGBClassifier(n_estimators = 300, max_depth = 3, tree_method = 'hist', random_state = 42, learning_rate = 0.1)

  model.fit(train_x_over, train_y_over)

  res = model.predict(X_val_fold)

  ocinka = f1_score(y_val_fold, res, average='macro')


  f1_full.append(ocinka)

print(np.mean(f1_full))

# imp = model.feature_importances_
# for i in range(4):
#   idx = np.argmax(imp[:10])
#   print(idx)
#   imp[idx] = -10

# print(model.feature_importances_)

# print(columns_on_train[11])

0.5842960335968888

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(train_x, train_y, test_size=0.25, random_state=1)

over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

train_x_ov, train_y_ov = over.fit_resample(X_train, y_train)

tl = RandomUnderSampler(sampling_strategy = 0.6)
train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

model = xgb.XGBClassifier(n_estimators = 300, max_depth = 3, tree_method = 'hist', random_state = 42, learning_rate = 0.1)

model.fit(train_x_over, train_y_over)

# res = model.predict(X_test)
importance = model.feature_importances_

imp = model.feature_importances_
for i in range(5):
  idx = np.argmax(imp[:10])
  print(f"f_{idx+1} = {imp[idx]}")
  imp[idx] = -10



# print(columns_on_train[9])
# print(columns_on_train[8])
# print(columns_on_train[3])
# print(columns_on_train[1])
print(importance)


zero_idx = np.where(importance == 0)[0]

print(zero_idx)

print(columns_on_train[zero_idx])

# print(f'{importance[9]}- {columns_on_train[9]}')

f_10 = 0.27065297961235046
f_2 = 0.07081113755702972
f_4 = 0.03396493196487427
f_9 = 0.03042672388255596
f_7 = 0.020621798932552338
[0.01777241 0.07081114 0.00954858 0.03396493 0.0189392  0.01859369
 0.0206218  0.01680858 0.03042672 0.27065298 0.02610124 0.01567884
 0.0531834  0.02229637 0.01235716 0.02351579 0.01383847 0.01920454
 0.01533313 0.02231849 0.01851236 0.01908551 0.0184091  0.01968455
 0.0260552  0.01981328 0.00883463 0.00362026 0.00735395 0.
 0.01463127 0.01522747 0.         0.01051749 0.01184868 0.0148446
 0.00460737 0.         0.         0.         0.         0.0117661
 0.         0.         0.         0.         0.         0.01271254
 0.03050821]
[29 32 37 38 39 40 42 43 44 45 46]
Index(['fc_19', 'fc_22', 'fc_27', 'fc_28', 'fc_29', 'fc_30', 'fc_32', 'fc_33',
       'fc_34', 'fc_35', 'fc_36'],
      dtype='object')

In [ ]:
over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

train_x_ov, train_y_ov = over.fit_resample(train_x, train_y)

under = RandomUnderSampler(sampling_strategy = 0.6, random_state = 42)
train_x_over, train_y_over = under.fit_resample(train_x_ov, train_y_ov)

model = xgb.XGBClassifier(n_estimators = 300, max_depth = 3, tree_method = 'hist', random_state = 42, learning_rate = 0.1)

model.fit(train_x_over, train_y_over)

res = model.predict(test_x)

In [ ]:
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedKFold
import numpy as np

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=45)

learning_rates = [0.3, 0.2, 0.15, 0.1, 0.05]
n_estimators_list = [50, 100, 150, 200, 300]

results = []

for lr in learning_rates:
    for n_est in n_estimators_list:
        f1_full = []

        for train_idx, val_idx in cv.split(train_x, train_y):
            X_train_fold = train_x[train_idx]
            X_val_fold = train_x[val_idx]

            y_train_fold = train_y[train_idx]
            y_val_fold = train_y[val_idx]

            over = RandomOverSampler(random_state=42, sampling_strategy=0.6)
            train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

            under = RandomUnderSampler(random_state=42, sampling_strategy=0.6)
            train_x_bal, train_y_bal = under.fit_resample(train_x_ov, train_y_ov)

            model = xgb.XGBClassifier(
                n_estimators=n_est,
                learning_rate=lr,
                max_depth=3,
                tree_method='hist',
                random_state=42,
                n_jobs=1
            )

            model.fit(train_x_bal, train_y_bal)

            pred = model.predict(X_val_fold)
            score = f1_score(y_val_fold, pred, average='macro')
            f1_full.append(score)

        mean_score = np.mean(f1_full)
        results.append((lr, n_est, mean_score))
        print(f"lr={lr}, n_estimators={n_est}, mean_f1={mean_score:.5f}")

best = max(results, key=lambda x: x[2])
print("\nBest:")
print(f"learning_rate={best[0]}, n_estimators={best[1]}, mean_f1={best[2]:.5f}")

lr=0.3, n_estimators=50, mean_f1=0.58190
lr=0.3, n_estimators=100, mean_f1=0.58357
lr=0.3, n_estimators=150, mean_f1=0.58200
lr=0.3, n_estimators=200, mean_f1=0.58050
lr=0.3, n_estimators=300, mean_f1=0.57480
lr=0.2, n_estimators=50, mean_f1=0.58080
lr=0.2, n_estimators=100, mean_f1=0.58189
lr=0.2, n_estimators=150, mean_f1=0.58264
lr=0.2, n_estimators=200, mean_f1=0.58184
lr=0.2, n_estimators=300, mean_f1=0.58030
lr=0.15, n_estimators=50, mean_f1=0.57989
lr=0.15, n_estimators=100, mean_f1=0.58283
lr=0.15, n_estimators=150, mean_f1=0.58396
lr=0.15, n_estimators=200, mean_f1=0.58261
lr=0.15, n_estimators=300, mean_f1=0.58340
lr=0.1, n_estimators=50, mean_f1=0.57960
lr=0.1, n_estimators=100, mean_f1=0.58167
lr=0.1, n_estimators=150, mean_f1=0.58392
lr=0.1, n_estimators=200, mean_f1=0.58473
lr=0.1, n_estimators=300, mean_f1=0.58442
lr=0.05, n_estimators=50, mean_f1=0.57267
lr=0.05, n_estimators=100, mean_f1=0.57835
lr=0.05, n_estimators=150, mean_f1=0.58055
lr=0.05, n_estimators=200, mean_f1=0.58157
lr=0.05, n_estimators=300, mean_f1=0.58391

Best:
learning_rate=0.1, n_estimators=200, mean_f1=0.58473

In [ ]:
features = [2, 4, 9, 10]

additional_df = pd.DataFrame()


for i in features:
  additional_df[f'f_{i}^2'] = train[f'f_{i}'] * train[f'f_{i}']

eps = 1e-6

additional_df['f_10_div_f2'] = train['f_10'] / (train['f_2'] + eps)

additional_df['f_10_div_f4'] = train['f_10'] / (train['f_4'] + eps)


additional_df['f_2_div_f4'] = train['f_2'] / (train['f_4'] + eps)


additional_df['f10_x_f2'] = train['f_10'] * train['f_2']


additional_df['f10_x_f4'] = train['f_10'] * train['f_4']


additional_df['f2_x_f4'] = train['f_2'] * train['f_4']


additional_df['f_9_is_zero'] = (train['f_9'] == 0).astype(int)


additional_df['f_10_is_zero'] = (train['f_10'] == 0).astype(int)

print(additional_df)

       f_2^2  f_4^2  f_9^2  f_10^2  f_10_div_f2  f_10_div_f4  f_2_div_f4  \
0        625      1      0       0     0.000000     0.000000   24.999975
1          1      9      0       0     0.000000     0.000000    0.333333
2          1      4      0       1     0.999999     0.500000    0.500000
3          1      4      0       0     0.000000     0.000000    0.500000
4          1      1      0       0     0.000000     0.000000    0.999999
...      ...    ...    ...     ...          ...          ...         ...
65160      1      4      1       1     0.999999     0.500000    0.500000
65161      1     25      0       1     0.999999     0.200000    0.200000
65162      1      1      0       0     0.000000     0.000000    0.999999
65163      1     36      1       4     1.999998     0.333333    0.166667
65164      1     36      0       0     0.000000     0.000000    0.166667

       f10_x_f2  f10_x_f4  f2_x_f4  f_9_is_zero  f_10_is_zero
0             0         0       25            1             1
1             0         0        3            1             1
2             1         2        2            1             0
3             0         0        2            1             1
4             0         0        1            1             1
...         ...       ...      ...          ...           ...
65160         1         2        2            0             0
65161         1         5        5            1             0
65162         0         0        1            1             1
65163         2        12        6            0             0
65164         0         0        6            1             1

[65165 rows x 12 columns]

In [ ]:
from itertools import combinations

new_features = [
    'f_2^2',
    'f_4^2',
    'f_9^2',
    'f_10^2',
    'f_10_div_f2',
    'f_10_div_f4',
    'f_2_div_f4',
    'f10_x_f2',
    'f10_x_f4',
    'f2_x_f4',
    'f_9_is_zero',
    'f_10_is_zero'
]

all_combinations = []

for r in range(1, len(new_features) + 1):   # r = 1, 2, 3, ..., 12
    for comb in combinations(new_features, r):
        all_combinations.append(list(comb))

Кількість усіх комбінацій: 4095
[['f_2^2'], ['f_4^2'], ['f_9^2'], ['f_10^2'], ['f_10_div_f2'], ['f_10_div_f4'], ['f_2_div_f4'], ['f10_x_f2'], ['f10_x_f4'], ['f2_x_f4'], ['f_9_is_zero'], ['f_10_is_zero'], ['f_2^2', 'f_4^2'], ['f_2^2', 'f_9^2'], ['f_2^2', 'f_10^2']]

In [ ]:

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

result = []

for i in all_combinations:

  df = np.hstack([train_x, additional_df[i]])

  f1_full = []
  for train_idx, val_idx in cv.split(df, train_y):

    X_train_fold = df[train_idx]
    X_val_fold = df[val_idx]

    y_train_fold = train_y[train_idx]
    y_val_fold = train_y[val_idx]

    over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

    train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

    tl = RandomUnderSampler(sampling_strategy = 0.6, random_state=42)
    train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

    model = xgb.XGBClassifier(n_estimators = 100, max_depth = 3, tree_method = 'hist', random_state = 42, n_jobs=1)

    model.fit(train_x_over, train_y_over)

    res = model.predict(X_val_fold)

    ocinka = f1_score(y_val_fold, res, average='macro')

    f1_full.append(ocinka)


  f1 = np.mean(f1_full)

  print(f1, i)

  result.append(f1)



print(np.max(result))

0.5831886734924164 ['f_2^2']
0.5831886734924164 ['f_4^2']
0.5831886734924164 ['f_9^2']
0.5831886734924164 ['f_10^2']
0.5840203931449215 ['f_10_div_f2']
0.5830757825852058 ['f_10_div_f4']
0.5842919407650171 ['f_2_div_f4']
0.5824467023650114 ['f10_x_f2']
0.5838451299081409 ['f10_x_f4']
0.5850709376067953 ['f2_x_f4']
0.5831886734924164 ['f_9_is_zero']
0.5831886734924164 ['f_10_is_zero']
0.5831886734924164 ['f_2^2', 'f_4^2']
0.5831886734924164 ['f_2^2', 'f_9^2']
0.5831886734924164 ['f_2^2', 'f_10^2']
0.5840203931449215 ['f_2^2', 'f_10_div_f2']
0.5830757825852058 ['f_2^2', 'f_10_div_f4']
0.5842919407650171 ['f_2^2', 'f_2_div_f4']
0.5824467023650114 ['f_2^2', 'f10_x_f2']
0.5838451299081409 ['f_2^2', 'f10_x_f4']
0.5850709376067953 ['f_2^2', 'f2_x_f4']
0.5831886734924164 ['f_2^2', 'f_9_is_zero']
0.5831886734924164 ['f_2^2', 'f_10_is_zero']
0.5831886734924164 ['f_4^2', 'f_9^2']
0.5831886734924164 ['f_4^2', 'f_10^2']
0.5840203931449215 ['f_4^2', 'f_10_div_f2']
0.5830757825852058 ['f_4^2', 'f_10_div_f4']
0.5842919407650171 ['f_4^2', 'f_2_div_f4']
0.5824467023650114 ['f_4^2', 'f10_x_f2']
0.5838451299081409 ['f_4^2', 'f10_x_f4']
0.5850709376067953 ['f_4^2', 'f2_x_f4']
0.5831886734924164 ['f_4^2', 'f_9_is_zero']
0.5831886734924164 ['f_4^2', 'f_10_is_zero']
0.5831886734924164 ['f_9^2', 'f_10^2']
0.5840203931449215 ['f_9^2', 'f_10_div_f2']
0.5830757825852058 ['f_9^2', 'f_10_div_f4']
0.5842919407650171 ['f_9^2', 'f_2_div_f4']
0.5824467023650114 ['f_9^2', 'f10_x_f2']
0.5838451299081409 ['f_9^2', 'f10_x_f4']
0.5850709376067953 ['f_9^2', 'f2_x_f4']
0.5831886734924164 ['f_9^2', 'f_9_is_zero']
0.5831886734924164 ['f_9^2', 'f_10_is_zero']
0.5840203931449215 ['f_10^2', 'f_10_div_f2']
0.5830757825852058 ['f_10^2', 'f_10_div_f4']
0.5842919407650171 ['f_10^2', 'f_2_div_f4']
0.5824467023650114 ['f_10^2', 'f10_x_f2']
0.5838451299081409 ['f_10^2', 'f10_x_f4']
0.5850709376067953 ['f_10^2', 'f2_x_f4']
0.5831886734924164 ['f_10^2', 'f_9_is_zero']
0.5831886734924164 ['f_10^2', 'f_10_is_zero']
0.5806301533536524 ['f_10_div_f2', 'f_10_div_f4']
0.5835050803834435 ['f_10_div_f2', 'f_2_div_f4']
0.58268889476142 ['f_10_div_f2', 'f10_x_f2']
0.5834968549706658 ['f_10_div_f2', 'f10_x_f4']
0.5828770711803614 ['f_10_div_f2', 'f2_x_f4']
0.5840203931449215 ['f_10_div_f2', 'f_9_is_zero']
0.5840203931449215 ['f_10_div_f2', 'f_10_is_zero']
0.5830377889969789 ['f_10_div_f4', 'f_2_div_f4']
0.5828581874191424 ['f_10_div_f4', 'f10_x_f2']
0.5822983942157407 ['f_10_div_f4', 'f10_x_f4']
0.5809835762609366 ['f_10_div_f4', 'f2_x_f4']
0.5830757825852058 ['f_10_div_f4', 'f_9_is_zero']
0.5830757825852058 ['f_10_div_f4', 'f_10_is_zero']
0.5820899912427491 ['f_2_div_f4', 'f10_x_f2']
0.5838965312703541 ['f_2_div_f4', 'f10_x_f4']
0.5806736579823151 ['f_2_div_f4', 'f2_x_f4']
0.5842919407650171 ['f_2_div_f4', 'f_9_is_zero']
0.5842919407650171 ['f_2_div_f4', 'f_10_is_zero']
0.5815875718244328 ['f10_x_f2', 'f10_x_f4']
0.5823229294009541 ['f10_x_f2', 'f2_x_f4']
0.5824467023650114 ['f10_x_f2', 'f_9_is_zero']
0.5824467023650114 ['f10_x_f2', 'f_10_is_zero']
0.5829948357071201 ['f10_x_f4', 'f2_x_f4']
0.5838451299081409 ['f10_x_f4', 'f_9_is_zero']
0.5838451299081409 ['f10_x_f4', 'f_10_is_zero']
0.5850709376067953 ['f2_x_f4', 'f_9_is_zero']
0.5850709376067953 ['f2_x_f4', 'f_10_is_zero']
0.5831886734924164 ['f_9_is_zero', 'f_10_is_zero']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_9^2']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_10^2']
0.5840203931449215 ['f_2^2', 'f_4^2', 'f_10_div_f2']
0.5830757825852058 ['f_2^2', 'f_4^2', 'f_10_div_f4']
0.5842919407650171 ['f_2^2', 'f_4^2', 'f_2_div_f4']
0.5824467023650114 ['f_2^2', 'f_4^2', 'f10_x_f2']
0.5838451299081409 ['f_2^2', 'f_4^2', 'f10_x_f4']
0.5850709376067953 ['f_2^2', 'f_4^2', 'f2_x_f4']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_9_is_zero']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_10_is_zero']
0.5831886734924164 ['f_2^2', 'f_9^2', 'f_10^2']
0.5840203931449215 ['f_2^2', 'f_9^2', 'f_10_div_f2']
0.5830757825852058 ['f_2^2', 'f_9^2', 'f_10_div_f4']
0.5842919407650171 ['f_2^2', 'f_9^2', 'f_2_div_f4']
0.5824467023650114 ['f_2^2', 'f_9^2', 'f10_x_f2']
0.5838451299081409 ['f_2^2', 'f_9^2', 'f10_x_f4']
0.5850709376067953 ['f_2^2', 'f_9^2', 'f2_x_f4']
0.5831886734924164 ['f_2^2', 'f_9^2', 'f_9_is_zero']
0.5831886734924164 ['f_2^2', 'f_9^2', 'f_10_is_zero']
0.5840203931449215 ['f_2^2', 'f_10^2', 'f_10_div_f2']
0.5830757825852058 ['f_2^2', 'f_10^2', 'f_10_div_f4']
0.5842919407650171 ['f_2^2', 'f_10^2', 'f_2_div_f4']
0.5824467023650114 ['f_2^2', 'f_10^2', 'f10_x_f2']
0.5838451299081409 ['f_2^2', 'f_10^2', 'f10_x_f4']
0.5850709376067953 ['f_2^2', 'f_10^2', 'f2_x_f4']
0.5831886734924164 ['f_2^2', 'f_10^2', 'f_9_is_zero']
0.5831886734924164 ['f_2^2', 'f_10^2', 'f_10_is_zero']
0.5806301533536524 ['f_2^2', 'f_10_div_f2', 'f_10_div_f4']
0.5835050803834435 ['f_2^2', 'f_10_div_f2', 'f_2_div_f4']
0.58268889476142 ['f_2^2', 'f_10_div_f2', 'f10_x_f2']
0.5834968549706658 ['f_2^2', 'f_10_div_f2', 'f10_x_f4']
0.5828770711803614 ['f_2^2', 'f_10_div_f2', 'f2_x_f4']
0.5840203931449215 ['f_2^2', 'f_10_div_f2', 'f_9_is_zero']
0.5840203931449215 ['f_2^2', 'f_10_div_f2', 'f_10_is_zero']
0.5830377889969789 ['f_2^2', 'f_10_div_f4', 'f_2_div_f4']
0.5828581874191424 ['f_2^2', 'f_10_div_f4', 'f10_x_f2']
0.5822983942157407 ['f_2^2', 'f_10_div_f4', 'f10_x_f4']
0.5809835762609366 ['f_2^2', 'f_10_div_f4', 'f2_x_f4']
0.5830757825852058 ['f_2^2', 'f_10_div_f4', 'f_9_is_zero']
0.5830757825852058 ['f_2^2', 'f_10_div_f4', 'f_10_is_zero']
0.5820899912427491 ['f_2^2', 'f_2_div_f4', 'f10_x_f2']
0.5838965312703541 ['f_2^2', 'f_2_div_f4', 'f10_x_f4']
0.5806736579823151 ['f_2^2', 'f_2_div_f4', 'f2_x_f4']
0.5842919407650171 ['f_2^2', 'f_2_div_f4', 'f_9_is_zero']
0.5842919407650171 ['f_2^2', 'f_2_div_f4', 'f_10_is_zero']
0.5815875718244328 ['f_2^2', 'f10_x_f2', 'f10_x_f4']
0.5823229294009541 ['f_2^2', 'f10_x_f2', 'f2_x_f4']
0.5824467023650114 ['f_2^2', 'f10_x_f2', 'f_9_is_zero']
0.5824467023650114 ['f_2^2', 'f10_x_f2', 'f_10_is_zero']
0.5829948357071201 ['f_2^2', 'f10_x_f4', 'f2_x_f4']
0.5838451299081409 ['f_2^2', 'f10_x_f4', 'f_9_is_zero']
0.5838451299081409 ['f_2^2', 'f10_x_f4', 'f_10_is_zero']
0.5850709376067953 ['f_2^2', 'f2_x_f4', 'f_9_is_zero']
0.5850709376067953 ['f_2^2', 'f2_x_f4', 'f_10_is_zero']
0.5831886734924164 ['f_2^2', 'f_9_is_zero', 'f_10_is_zero']
0.5831886734924164 ['f_4^2', 'f_9^2', 'f_10^2']
0.5840203931449215 ['f_4^2', 'f_9^2', 'f_10_div_f2']
0.5830757825852058 ['f_4^2', 'f_9^2', 'f_10_div_f4']
0.5842919407650171 ['f_4^2', 'f_9^2', 'f_2_div_f4']
0.5824467023650114 ['f_4^2', 'f_9^2', 'f10_x_f2']
0.5838451299081409 ['f_4^2', 'f_9^2', 'f10_x_f4']
0.5850709376067953 ['f_4^2', 'f_9^2', 'f2_x_f4']
0.5831886734924164 ['f_4^2', 'f_9^2', 'f_9_is_zero']
0.5831886734924164 ['f_4^2', 'f_9^2', 'f_10_is_zero']
0.5840203931449215 ['f_4^2', 'f_10^2', 'f_10_div_f2']
0.5830757825852058 ['f_4^2', 'f_10^2', 'f_10_div_f4']
0.5842919407650171 ['f_4^2', 'f_10^2', 'f_2_div_f4']
0.5824467023650114 ['f_4^2', 'f_10^2', 'f10_x_f2']
0.5838451299081409 ['f_4^2', 'f_10^2', 'f10_x_f4']
0.5850709376067953 ['f_4^2', 'f_10^2', 'f2_x_f4']
0.5831886734924164 ['f_4^2', 'f_10^2', 'f_9_is_zero']
0.5831886734924164 ['f_4^2', 'f_10^2', 'f_10_is_zero']
0.5806301533536524 ['f_4^2', 'f_10_div_f2', 'f_10_div_f4']
0.5835050803834435 ['f_4^2', 'f_10_div_f2', 'f_2_div_f4']
0.58268889476142 ['f_4^2', 'f_10_div_f2', 'f10_x_f2']
0.5834968549706658 ['f_4^2', 'f_10_div_f2', 'f10_x_f4']
0.5828770711803614 ['f_4^2', 'f_10_div_f2', 'f2_x_f4']
0.5840203931449215 ['f_4^2', 'f_10_div_f2', 'f_9_is_zero']
0.5840203931449215 ['f_4^2', 'f_10_div_f2', 'f_10_is_zero']
0.5830377889969789 ['f_4^2', 'f_10_div_f4', 'f_2_div_f4']
0.5828581874191424 ['f_4^2', 'f_10_div_f4', 'f10_x_f2']
0.5822983942157407 ['f_4^2', 'f_10_div_f4', 'f10_x_f4']
0.5809835762609366 ['f_4^2', 'f_10_div_f4', 'f2_x_f4']
0.5830757825852058 ['f_4^2', 'f_10_div_f4', 'f_9_is_zero']
0.5830757825852058 ['f_4^2', 'f_10_div_f4', 'f_10_is_zero']
0.5820899912427491 ['f_4^2', 'f_2_div_f4', 'f10_x_f2']
0.5838965312703541 ['f_4^2', 'f_2_div_f4', 'f10_x_f4']
0.5806736579823151 ['f_4^2', 'f_2_div_f4', 'f2_x_f4']
0.5842919407650171 ['f_4^2', 'f_2_div_f4', 'f_9_is_zero']
0.5842919407650171 ['f_4^2', 'f_2_div_f4', 'f_10_is_zero']
0.5815875718244328 ['f_4^2', 'f10_x_f2', 'f10_x_f4']
0.5823229294009541 ['f_4^2', 'f10_x_f2', 'f2_x_f4']
0.5824467023650114 ['f_4^2', 'f10_x_f2', 'f_9_is_zero']
0.5824467023650114 ['f_4^2', 'f10_x_f2', 'f_10_is_zero']
0.5829948357071201 ['f_4^2', 'f10_x_f4', 'f2_x_f4']
0.5838451299081409 ['f_4^2', 'f10_x_f4', 'f_9_is_zero']
0.5838451299081409 ['f_4^2', 'f10_x_f4', 'f_10_is_zero']
0.5850709376067953 ['f_4^2', 'f2_x_f4', 'f_9_is_zero']
0.5850709376067953 ['f_4^2', 'f2_x_f4', 'f_10_is_zero']
0.5831886734924164 ['f_4^2', 'f_9_is_zero', 'f_10_is_zero']
0.5840203931449215 ['f_9^2', 'f_10^2', 'f_10_div_f2']
0.5830757825852058 ['f_9^2', 'f_10^2', 'f_10_div_f4']
0.5842919407650171 ['f_9^2', 'f_10^2', 'f_2_div_f4']
0.5824467023650114 ['f_9^2', 'f_10^2', 'f10_x_f2']
0.5838451299081409 ['f_9^2', 'f_10^2', 'f10_x_f4']
0.5850709376067953 ['f_9^2', 'f_10^2', 'f2_x_f4']
0.5831886734924164 ['f_9^2', 'f_10^2', 'f_9_is_zero']
0.5831886734924164 ['f_9^2', 'f_10^2', 'f_10_is_zero']
0.5806301533536524 ['f_9^2', 'f_10_div_f2', 'f_10_div_f4']
0.5835050803834435 ['f_9^2', 'f_10_div_f2', 'f_2_div_f4']
0.58268889476142 ['f_9^2', 'f_10_div_f2', 'f10_x_f2']
0.5834968549706658 ['f_9^2', 'f_10_div_f2', 'f10_x_f4']
0.5828770711803614 ['f_9^2', 'f_10_div_f2', 'f2_x_f4']
0.5840203931449215 ['f_9^2', 'f_10_div_f2', 'f_9_is_zero']
0.5840203931449215 ['f_9^2', 'f_10_div_f2', 'f_10_is_zero']
0.5830377889969789 ['f_9^2', 'f_10_div_f4', 'f_2_div_f4']
0.5828581874191424 ['f_9^2', 'f_10_div_f4', 'f10_x_f2']
0.5822983942157407 ['f_9^2', 'f_10_div_f4', 'f10_x_f4']
0.5809835762609366 ['f_9^2', 'f_10_div_f4', 'f2_x_f4']
0.5830757825852058 ['f_9^2', 'f_10_div_f4', 'f_9_is_zero']
0.5830757825852058 ['f_9^2', 'f_10_div_f4', 'f_10_is_zero']
0.5820899912427491 ['f_9^2', 'f_2_div_f4', 'f10_x_f2']
0.5838965312703541 ['f_9^2', 'f_2_div_f4', 'f10_x_f4']
0.5806736579823151 ['f_9^2', 'f_2_div_f4', 'f2_x_f4']
0.5842919407650171 ['f_9^2', 'f_2_div_f4', 'f_9_is_zero']
0.5842919407650171 ['f_9^2', 'f_2_div_f4', 'f_10_is_zero']
0.5815875718244328 ['f_9^2', 'f10_x_f2', 'f10_x_f4']
0.5823229294009541 ['f_9^2', 'f10_x_f2', 'f2_x_f4']
0.5824467023650114 ['f_9^2', 'f10_x_f2', 'f_9_is_zero']
0.5824467023650114 ['f_9^2', 'f10_x_f2', 'f_10_is_zero']
0.5829948357071201 ['f_9^2', 'f10_x_f4', 'f2_x_f4']
0.5838451299081409 ['f_9^2', 'f10_x_f4', 'f_9_is_zero']
0.5838451299081409 ['f_9^2', 'f10_x_f4', 'f_10_is_zero']
0.5850709376067953 ['f_9^2', 'f2_x_f4', 'f_9_is_zero']
0.5850709376067953 ['f_9^2', 'f2_x_f4', 'f_10_is_zero']
0.5831886734924164 ['f_9^2', 'f_9_is_zero', 'f_10_is_zero']
0.5806301533536524 ['f_10^2', 'f_10_div_f2', 'f_10_div_f4']
0.5835050803834435 ['f_10^2', 'f_10_div_f2', 'f_2_div_f4']
0.58268889476142 ['f_10^2', 'f_10_div_f2', 'f10_x_f2']
0.5834968549706658 ['f_10^2', 'f_10_div_f2', 'f10_x_f4']
0.5828770711803614 ['f_10^2', 'f_10_div_f2', 'f2_x_f4']
0.5840203931449215 ['f_10^2', 'f_10_div_f2', 'f_9_is_zero']
0.5840203931449215 ['f_10^2', 'f_10_div_f2', 'f_10_is_zero']
0.5830377889969789 ['f_10^2', 'f_10_div_f4', 'f_2_div_f4']
0.5828581874191424 ['f_10^2', 'f_10_div_f4', 'f10_x_f2']
0.5822983942157407 ['f_10^2', 'f_10_div_f4', 'f10_x_f4']
0.5809835762609366 ['f_10^2', 'f_10_div_f4', 'f2_x_f4']
0.5830757825852058 ['f_10^2', 'f_10_div_f4', 'f_9_is_zero']
0.5830757825852058 ['f_10^2', 'f_10_div_f4', 'f_10_is_zero']
0.5820899912427491 ['f_10^2', 'f_2_div_f4', 'f10_x_f2']
0.5838965312703541 ['f_10^2', 'f_2_div_f4', 'f10_x_f4']
0.5806736579823151 ['f_10^2', 'f_2_div_f4', 'f2_x_f4']
0.5842919407650171 ['f_10^2', 'f_2_div_f4', 'f_9_is_zero']
0.5842919407650171 ['f_10^2', 'f_2_div_f4', 'f_10_is_zero']
0.5815875718244328 ['f_10^2', 'f10_x_f2', 'f10_x_f4']
0.5823229294009541 ['f_10^2', 'f10_x_f2', 'f2_x_f4']
0.5824467023650114 ['f_10^2', 'f10_x_f2', 'f_9_is_zero']
0.5824467023650114 ['f_10^2', 'f10_x_f2', 'f_10_is_zero']
0.5829948357071201 ['f_10^2', 'f10_x_f4', 'f2_x_f4']
0.5838451299081409 ['f_10^2', 'f10_x_f4', 'f_9_is_zero']
0.5838451299081409 ['f_10^2', 'f10_x_f4', 'f_10_is_zero']
0.5850709376067953 ['f_10^2', 'f2_x_f4', 'f_9_is_zero']
0.5850709376067953 ['f_10^2', 'f2_x_f4', 'f_10_is_zero']
0.5831886734924164 ['f_10^2', 'f_9_is_zero', 'f_10_is_zero']
0.5814471997285358 ['f_10_div_f2', 'f_10_div_f4', 'f_2_div_f4']
0.5830430192286098 ['f_10_div_f2', 'f_10_div_f4', 'f10_x_f2']
0.5841373982329375 ['f_10_div_f2', 'f_10_div_f4', 'f10_x_f4']
0.5829376281572436 ['f_10_div_f2', 'f_10_div_f4', 'f2_x_f4']
0.5806301533536524 ['f_10_div_f2', 'f_10_div_f4', 'f_9_is_zero']
0.5806301533536524 ['f_10_div_f2', 'f_10_div_f4', 'f_10_is_zero']
0.5835307154349477 ['f_10_div_f2', 'f_2_div_f4', 'f10_x_f2']
0.583327864616147 ['f_10_div_f2', 'f_2_div_f4', 'f10_x_f4']
0.5822152775611524 ['f_10_div_f2', 'f_2_div_f4', 'f2_x_f4']
0.5835050803834435 ['f_10_div_f2', 'f_2_div_f4', 'f_9_is_zero']
0.5835050803834435 ['f_10_div_f2', 'f_2_div_f4', 'f_10_is_zero']
0.5812483041679203 ['f_10_div_f2', 'f10_x_f2', 'f10_x_f4']
0.5834610644182717 ['f_10_div_f2', 'f10_x_f2', 'f2_x_f4']
0.58268889476142 ['f_10_div_f2', 'f10_x_f2', 'f_9_is_zero']
0.58268889476142 ['f_10_div_f2', 'f10_x_f2', 'f_10_is_zero']
0.5821360986449782 ['f_10_div_f2', 'f10_x_f4', 'f2_x_f4']
0.5834968549706658 ['f_10_div_f2', 'f10_x_f4', 'f_9_is_zero']
0.5834968549706658 ['f_10_div_f2', 'f10_x_f4', 'f_10_is_zero']
0.5828770711803614 ['f_10_div_f2', 'f2_x_f4', 'f_9_is_zero']
0.5828770711803614 ['f_10_div_f2', 'f2_x_f4', 'f_10_is_zero']
0.5840203931449215 ['f_10_div_f2', 'f_9_is_zero', 'f_10_is_zero']
0.5822037509853494 ['f_10_div_f4', 'f_2_div_f4', 'f10_x_f2']
0.5822260675838422 ['f_10_div_f4', 'f_2_div_f4', 'f10_x_f4']
0.5825605467934791 ['f_10_div_f4', 'f_2_div_f4', 'f2_x_f4']
0.5830377889969789 ['f_10_div_f4', 'f_2_div_f4', 'f_9_is_zero']
0.5830377889969789 ['f_10_div_f4', 'f_2_div_f4', 'f_10_is_zero']
0.5815277017382197 ['f_10_div_f4', 'f10_x_f2', 'f10_x_f4']
0.5826534889376259 ['f_10_div_f4', 'f10_x_f2', 'f2_x_f4']
0.5828581874191424 ['f_10_div_f4', 'f10_x_f2', 'f_9_is_zero']
0.5828581874191424 ['f_10_div_f4', 'f10_x_f2', 'f_10_is_zero']
0.583510489094388 ['f_10_div_f4', 'f10_x_f4', 'f2_x_f4']
0.5822983942157407 ['f_10_div_f4', 'f10_x_f4', 'f_9_is_zero']
0.5822983942157407 ['f_10_div_f4', 'f10_x_f4', 'f_10_is_zero']
0.5809835762609366 ['f_10_div_f4', 'f2_x_f4', 'f_9_is_zero']
0.5809835762609366 ['f_10_div_f4', 'f2_x_f4', 'f_10_is_zero']
0.5830757825852058 ['f_10_div_f4', 'f_9_is_zero', 'f_10_is_zero']
0.5831840493073084 ['f_2_div_f4', 'f10_x_f2', 'f10_x_f4']
0.5822502524102893 ['f_2_div_f4', 'f10_x_f2', 'f2_x_f4']
0.5820899912427491 ['f_2_div_f4', 'f10_x_f2', 'f_9_is_zero']
0.5820899912427491 ['f_2_div_f4', 'f10_x_f2', 'f_10_is_zero']
0.5832494881412478 ['f_2_div_f4', 'f10_x_f4', 'f2_x_f4']
0.5838965312703541 ['f_2_div_f4', 'f10_x_f4', 'f_9_is_zero']
0.5838965312703541 ['f_2_div_f4', 'f10_x_f4', 'f_10_is_zero']
0.5806736579823151 ['f_2_div_f4', 'f2_x_f4', 'f_9_is_zero']
0.5806736579823151 ['f_2_div_f4', 'f2_x_f4', 'f_10_is_zero']
0.5842919407650171 ['f_2_div_f4', 'f_9_is_zero', 'f_10_is_zero']
0.5816769544527405 ['f10_x_f2', 'f10_x_f4', 'f2_x_f4']
0.5815875718244328 ['f10_x_f2', 'f10_x_f4', 'f_9_is_zero']
0.5815875718244328 ['f10_x_f2', 'f10_x_f4', 'f_10_is_zero']
0.5823229294009541 ['f10_x_f2', 'f2_x_f4', 'f_9_is_zero']
0.5823229294009541 ['f10_x_f2', 'f2_x_f4', 'f_10_is_zero']
0.5824467023650114 ['f10_x_f2', 'f_9_is_zero', 'f_10_is_zero']
0.5829948357071201 ['f10_x_f4', 'f2_x_f4', 'f_9_is_zero']
0.5829948357071201 ['f10_x_f4', 'f2_x_f4', 'f_10_is_zero']
0.5838451299081409 ['f10_x_f4', 'f_9_is_zero', 'f_10_is_zero']
0.5850709376067953 ['f2_x_f4', 'f_9_is_zero', 'f_10_is_zero']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_9^2', 'f_10^2']
0.5840203931449215 ['f_2^2', 'f_4^2', 'f_9^2', 'f_10_div_f2']
0.5830757825852058 ['f_2^2', 'f_4^2', 'f_9^2', 'f_10_div_f4']
0.5842919407650171 ['f_2^2', 'f_4^2', 'f_9^2', 'f_2_div_f4']
0.5824467023650114 ['f_2^2', 'f_4^2', 'f_9^2', 'f10_x_f2']
0.5838451299081409 ['f_2^2', 'f_4^2', 'f_9^2', 'f10_x_f4']
0.5850709376067953 ['f_2^2', 'f_4^2', 'f_9^2', 'f2_x_f4']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_9^2', 'f_9_is_zero']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_9^2', 'f_10_is_zero']
0.5840203931449215 ['f_2^2', 'f_4^2', 'f_10^2', 'f_10_div_f2']
0.5830757825852058 ['f_2^2', 'f_4^2', 'f_10^2', 'f_10_div_f4']
0.5842919407650171 ['f_2^2', 'f_4^2', 'f_10^2', 'f_2_div_f4']
0.5824467023650114 ['f_2^2', 'f_4^2', 'f_10^2', 'f10_x_f2']
0.5838451299081409 ['f_2^2', 'f_4^2', 'f_10^2', 'f10_x_f4']
0.5850709376067953 ['f_2^2', 'f_4^2', 'f_10^2', 'f2_x_f4']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_10^2', 'f_9_is_zero']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_10^2', 'f_10_is_zero']
0.5806301533536524 ['f_2^2', 'f_4^2', 'f_10_div_f2', 'f_10_div_f4']
0.5835050803834435 ['f_2^2', 'f_4^2', 'f_10_div_f2', 'f_2_div_f4']
0.58268889476142 ['f_2^2', 'f_4^2', 'f_10_div_f2', 'f10_x_f2']
0.5834968549706658 ['f_2^2', 'f_4^2', 'f_10_div_f2', 'f10_x_f4']
0.5828770711803614 ['f_2^2', 'f_4^2', 'f_10_div_f2', 'f2_x_f4']
0.5840203931449215 ['f_2^2', 'f_4^2', 'f_10_div_f2', 'f_9_is_zero']
0.5840203931449215 ['f_2^2', 'f_4^2', 'f_10_div_f2', 'f_10_is_zero']
0.5830377889969789 ['f_2^2', 'f_4^2', 'f_10_div_f4', 'f_2_div_f4']
0.5828581874191424 ['f_2^2', 'f_4^2', 'f_10_div_f4', 'f10_x_f2']
0.5822983942157407 ['f_2^2', 'f_4^2', 'f_10_div_f4', 'f10_x_f4']
0.5809835762609366 ['f_2^2', 'f_4^2', 'f_10_div_f4', 'f2_x_f4']
0.5830757825852058 ['f_2^2', 'f_4^2', 'f_10_div_f4', 'f_9_is_zero']
0.5830757825852058 ['f_2^2', 'f_4^2', 'f_10_div_f4', 'f_10_is_zero']
0.5820899912427491 ['f_2^2', 'f_4^2', 'f_2_div_f4', 'f10_x_f2']
0.5838965312703541 ['f_2^2', 'f_4^2', 'f_2_div_f4', 'f10_x_f4']
0.5806736579823151 ['f_2^2', 'f_4^2', 'f_2_div_f4', 'f2_x_f4']
0.5842919407650171 ['f_2^2', 'f_4^2', 'f_2_div_f4', 'f_9_is_zero']
0.5842919407650171 ['f_2^2', 'f_4^2', 'f_2_div_f4', 'f_10_is_zero']
0.5815875718244328 ['f_2^2', 'f_4^2', 'f10_x_f2', 'f10_x_f4']
0.5823229294009541 ['f_2^2', 'f_4^2', 'f10_x_f2', 'f2_x_f4']
0.5824467023650114 ['f_2^2', 'f_4^2', 'f10_x_f2', 'f_9_is_zero']
0.5824467023650114 ['f_2^2', 'f_4^2', 'f10_x_f2', 'f_10_is_zero']
0.5829948357071201 ['f_2^2', 'f_4^2', 'f10_x_f4', 'f2_x_f4']
0.5838451299081409 ['f_2^2', 'f_4^2', 'f10_x_f4', 'f_9_is_zero']
0.5838451299081409 ['f_2^2', 'f_4^2', 'f10_x_f4', 'f_10_is_zero']
0.5850709376067953 ['f_2^2', 'f_4^2', 'f2_x_f4', 'f_9_is_zero']
0.5850709376067953 ['f_2^2', 'f_4^2', 'f2_x_f4', 'f_10_is_zero']
0.5831886734924164 ['f_2^2', 'f_4^2', 'f_9_is_zero', 'f_10_is_zero']
0.5840203931449215 ['f_2^2', 'f_9^2', 'f_10^2', 'f_10_div_f2']
0.5830757825852058 ['f_2^2', 'f_9^2', 'f_10^2', 'f_10_div_f4']
0.5842919407650171 ['f_2^2', 'f_9^2', 'f_10^2', 'f_2_div_f4']
0.5824467023650114 ['f_2^2', 'f_9^2', 'f_10^2', 'f10_x_f2']
0.5838451299081409 ['f_2^2', 'f_9^2', 'f_10^2', 'f10_x_f4']
0.5850709376067953 ['f_2^2', 'f_9^2', 'f_10^2', 'f2_x_f4']
0.5831886734924164 ['f_2^2', 'f_9^2', 'f_10^2', 'f_9_is_zero']
0.5831886734924164 ['f_2^2', 'f_9^2', 'f_10^2', 'f_10_is_zero']
0.5806301533536524 ['f_2^2', 'f_9^2', 'f_10_div_f2', 'f_10_div_f4']
0.5835050803834435 ['f_2^2', 'f_9^2', 'f_10_div_f2', 'f_2_div_f4']
0.58268889476142 ['f_2^2', 'f_9^2', 'f_10_div_f2', 'f10_x_f2']
0.5834968549706658 ['f_2^2', 'f_9^2', 'f_10_div_f2', 'f10_x_f4']
0.5828770711803614 ['f_2^2', 'f_9^2', 'f_10_div_f2', 'f2_x_f4']
0.5840203931449215 ['f_2^2', 'f_9^2', 'f_10_div_f2', 'f_9_is_zero']
0.5840203931449215 ['f_2^2', 'f_9^2', 'f_10_div_f2', 'f_10_is_zero']
0.5830377889969789 ['f_2^2', 'f_9^2', 'f_10_div_f4', 'f_2_div_f4']
0.5828581874191424 ['f_2^2', 'f_9^2', 'f_10_div_f4', 'f10_x_f2']
0.5822983942157407 ['f_2^2', 'f_9^2', 'f_10_div_f4', 'f10_x_f4']
0.5809835762609366 ['f_2^2', 'f_9^2', 'f_10_div_f4', 'f2_x_f4']
0.5830757825852058 ['f_2^2', 'f_9^2', 'f_10_div_f4', 'f_9_is_zero']

In [ ]:
indexs = [i for i, x in enumerate(result) if abs(x - 0.5850709376067953) < 1e-9]

In [ ]:
optimal_features = [all_combinations[i] for i in indexs]

In [ ]:
from collections import Counter


# Зливаємо всі підсписки в один список
all_features = [feat for combo in optimal_features for feat in combo]

# Рахуємо кількість появ кожної фічі
feature_counts = Counter(all_features)

print(feature_counts)

Counter({'f2_x_f4': 64, 'f_2^2': 32, 'f_4^2': 32, 'f_9^2': 32, 'f_10^2': 32, 'f_9_is_zero': 32, 'f_10_is_zero': 32})

In [ ]:
cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=41)

results = []

for comb in optimal_features:
    df = train_x

    f1_full = []

    for train_idx, val_idx in cv.split(df, train_y):
        X_train_fold = df[train_idx]
        X_val_fold = df[val_idx]

        y_train_fold = train_y[train_idx]
        y_val_fold = train_y[val_idx]

        over = RandomOverSampler(random_state=42, sampling_strategy=0.6)
        train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

        tl = RandomUnderSampler(sampling_strategy=0.6, random_state=42)
        train_x_over, train_y_over = tl.fit_resample(train_x_ov, train_y_ov)

        model = xgb.XGBClassifier(
            n_estimators=100,
            max_depth=3,
            tree_method='hist',
            random_state=42
        )

        model.fit(train_x_over, train_y_over)
        res = model.predict(X_val_fold)

        score = f1_score(y_val_fold, res, average='macro')
        f1_full.append(score)

    mean_f1 = np.mean(f1_full)
    std_f1 = np.std(f1_full)

    results.append({
        'combination': comb,
        'mean_f1': mean_f1,
        'std_f1': std_f1,
        'num_features': len(comb),
        'fold_scores': f1_full
    })

# сортуємо:
# 1) по mean_f1 за спаданням
# 2) по std_f1 за зростанням
# 3) по num_features за зростанням
results = sorted(results, key=lambda x: (-x['mean_f1'], x['std_f1'], x['num_features']))

best = results[0]

print("Best combination:", best['combination'])
print("Mean F1:", best['mean_f1'])
print("Std F1:", best['std_f1'])
print("Fold scores:", best['fold_scores'])

Best combination: ['f2_x_f4']
Mean F1: 0.5812676129334138
Std F1: 0.002920617831251312
Fold scores: [0.5839470828425597, 0.5820373909429113, 0.5827366750329304, 0.5763493029152539]

In [ ]:
features = [2, 4, 9, 10]

additional_df = pd.DataFrame()


for i in features:
  additional_df[f'f_{i}^2'] = train[f'f_{i}'] * train[f'f_{i}']

eps = 1e-6


additional_df['f_2_div_f4'] = train['f_2'] / (train['f_4'] + eps)


additional_df['f10_x_f2'] = train['f_10'] * train['f_2']

additional_df['f10_x_f4'] = train['f_10'] * train['f_4']

additional_df['f2_x_f4'] = train['f_2'] * train['f_4']

In [ ]:
from itertools import combinations
import numpy as np
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score

train = pd.read_csv('train.csv')
train_x = train.drop(columns=['target', 'id']).values
train_y = train['target'].values


cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

learning_rates = [0.3, 0.2, 0.15, 0.1, 0.05]
n_estimators_list = [50, 100, 150, 200, 300]
over_sampl = [0.2 , 0.6, 0.9, 1]
under_sampl = [0.2, 0.6, 0.9, 1]

depth_max = [1, 2, 3, 5]

new_features = [
    'f_2_div_f4',
    'f10_x_f2',
    'f10_x_f4',
    'f2_x_f4',
]

all_combinations = []
for r in range(1, len(new_features) + 1):
    for comb in combinations(new_features, r):
        all_combinations.append(list(comb))

results = []

for feat_comb in all_combinations:

    df = np.hstack([train_x, additional_df[feat_comb].values])

    for lr in learning_rates:
        for n_est in n_estimators_list:
            for over_s in over_sampl:
                for under_s in under_sampl:




                  if over_s > under_s:
                    continue

                  for depth in depth_max:

                        f1_full = []

                        for train_idx, val_idx in cv.split(df, train_y):

                            X_train_fold = df[train_idx]
                            X_val_fold = df[val_idx]

                            y_train_fold = train_y[train_idx]
                            y_val_fold = train_y[val_idx]

                            over = RandomOverSampler(random_state=42, sampling_strategy=over_s)
                            X_over, y_over = over.fit_resample(X_train_fold, y_train_fold)

                            under = RandomUnderSampler(random_state=42, sampling_strategy=under_s)
                            X_bal, y_bal = under.fit_resample(X_over, y_over)

                            model = xgb.XGBClassifier(
                                n_estimators=n_est,
                                learning_rate=lr,
                                max_depth=depth,
                                tree_method='hist',
                                random_state=42,
                                n_jobs=1
                            )

                            model.fit(X_bal, y_bal)

                            pred = model.predict(X_val_fold)
                            score = f1_score(y_val_fold, pred, average='macro')

                            f1_full.append(score)

                        mean_f1 = np.mean(f1_full)

                        print(f"F1={mean_f1:.5f} | feats={feat_comb} | lr={lr} | n_est={n_est} | over={over_s} | under={under_s} | depth={depth}")

                        results.append({
                            'f1': mean_f1,
                            'features': feat_comb,
                            'lr': lr,
                            'n_estimators': n_est,
                            'over_sampling': over_s,
                            'under_sampling': under_s,
                            'max_depth': depth
                        })

results_sorted = sorted(results, key=lambda x: x['f1'], reverse=True)

print("\nTOP 10")
for i in range(10):
    r = results_sorted[i]
    print(f"{i+1}) F1={r['f1']:.5f} | feats={r['features']} | lr={r['lr']} | n_est={r['n_estimators']} | over={r['over_sampling']} | under={r['under_sampling']} | depth={r['max_depth']}")

Выходные данные были обрезаны до нескольких последних строк (5000).
F1=0.54143 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=150 | over=0.9 | under=1 | depth=5
F1=0.53575 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=150 | over=1 | under=1 | depth=1
F1=0.52211 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=150 | over=1 | under=1 | depth=2
F1=0.52557 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=150 | over=1 | under=1 | depth=3
F1=0.53796 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=150 | over=1 | under=1 | depth=5
F1=0.48292 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.2 | depth=1
F1=0.49345 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.2 | depth=2
F1=0.49799 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.2 | depth=3
F1=0.50503 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.2 | depth=5
F1=0.57281 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.6 | depth=1
F1=0.58082 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.6 | depth=2
F1=0.58147 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.6 | depth=3
F1=0.58027 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.6 | depth=5
F1=0.55289 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.9 | depth=1
F1=0.54622 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.9 | depth=2
F1=0.54494 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.9 | depth=3
F1=0.54642 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=0.9 | depth=5
F1=0.53479 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=1 | depth=1
F1=0.52361 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=1 | depth=2
F1=0.52430 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=1 | depth=3
F1=0.52543 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.2 | under=1 | depth=5
F1=0.57480 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.6 | depth=1
F1=0.58268 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.6 | depth=2
F1=0.58320 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.6 | depth=3
F1=0.58068 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.6 | depth=5
F1=0.55403 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.9 | depth=1
F1=0.54781 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.9 | depth=2
F1=0.55015 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.9 | depth=3
F1=0.55541 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=0.9 | depth=5
F1=0.53605 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=1 | depth=1
F1=0.52331 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=1 | depth=2
F1=0.52628 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=1 | depth=3
F1=0.53822 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.6 | under=1 | depth=5
F1=0.55440 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=0.9 | depth=1
F1=0.55014 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=0.9 | depth=2
F1=0.54999 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=0.9 | depth=3
F1=0.55647 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=0.9 | depth=5
F1=0.53514 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=1 | depth=1
F1=0.52221 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=1 | depth=2
F1=0.52804 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=1 | depth=3
F1=0.54213 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=0.9 | under=1 | depth=5
F1=0.53498 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=1 | under=1 | depth=1
F1=0.52256 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=1 | under=1 | depth=2
F1=0.52560 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=1 | under=1 | depth=3
F1=0.54002 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=200 | over=1 | under=1 | depth=5
F1=0.48553 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.2 | depth=1
F1=0.49631 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.2 | depth=2
F1=0.50182 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.2 | depth=3
F1=0.50646 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.2 | depth=5
F1=0.57641 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.6 | depth=1
F1=0.58111 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.6 | depth=2
F1=0.58136 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.6 | depth=3
F1=0.57775 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.6 | depth=5
F1=0.55455 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.9 | depth=1
F1=0.54425 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.9 | depth=2
F1=0.54308 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.9 | depth=3
F1=0.54464 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=0.9 | depth=5
F1=0.53530 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=1 | depth=1
F1=0.52302 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=1 | depth=2
F1=0.52452 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=1 | depth=3
F1=0.52701 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.2 | under=1 | depth=5
F1=0.57765 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.6 | depth=1
F1=0.58227 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.6 | depth=2
F1=0.58411 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.6 | depth=3
F1=0.57750 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.6 | depth=5
F1=0.55601 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.9 | depth=1
F1=0.54717 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.9 | depth=2
F1=0.55021 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.9 | depth=3
F1=0.55779 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=0.9 | depth=5
F1=0.53780 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=1 | depth=1
F1=0.52387 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=1 | depth=2
F1=0.52886 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=1 | depth=3
F1=0.54373 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.6 | under=1 | depth=5
F1=0.55630 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=0.9 | depth=1
F1=0.54873 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=0.9 | depth=2
F1=0.55148 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=0.9 | depth=3
F1=0.55761 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=0.9 | depth=5
F1=0.53667 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=1 | depth=1
F1=0.52345 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=1 | depth=2
F1=0.53059 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=1 | depth=3
F1=0.54659 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=0.9 | under=1 | depth=5
F1=0.53651 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=1 | under=1 | depth=1
F1=0.52422 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=1 | under=1 | depth=2
F1=0.52899 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=1 | under=1 | depth=3
F1=0.54407 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.1 | n_est=300 | over=1 | under=1 | depth=5
F1=0.47015 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.2 | depth=1
F1=0.47217 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.2 | depth=2
F1=0.47792 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.2 | depth=3
F1=0.48391 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.2 | depth=5
F1=0.55761 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.6 | depth=1
F1=0.56272 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.6 | depth=2
F1=0.57432 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.6 | depth=3
F1=0.57895 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.6 | depth=5
F1=0.54955 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.9 | depth=1
F1=0.54505 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.9 | depth=2
F1=0.54851 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.9 | depth=3
F1=0.54805 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=0.9 | depth=5
F1=0.52243 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=1 | depth=1
F1=0.52374 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=1 | depth=2
F1=0.50926 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=1 | depth=3
F1=0.52266 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.2 | under=1 | depth=5
F1=0.56040 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.6 | depth=1
F1=0.56579 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.6 | depth=2
F1=0.57477 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.6 | depth=3
F1=0.57825 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.6 | depth=5
F1=0.55000 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.9 | depth=1
F1=0.54810 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.9 | depth=2
F1=0.54822 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.9 | depth=3
F1=0.55247 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=0.9 | depth=5
F1=0.53095 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=1 | depth=1
F1=0.52559 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=1 | depth=2
F1=0.51169 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=1 | depth=3
F1=0.52445 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.6 | under=1 | depth=5
F1=0.54934 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=0.9 | depth=1
F1=0.54916 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=0.9 | depth=2
F1=0.54828 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=0.9 | depth=3
F1=0.55110 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=0.9 | depth=5
F1=0.52768 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=1 | depth=1
F1=0.52232 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=1 | depth=2
F1=0.51031 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=1 | depth=3
F1=0.52515 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=0.9 | under=1 | depth=5
F1=0.51949 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=1 | under=1 | depth=1
F1=0.52220 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=1 | under=1 | depth=2
F1=0.51175 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=1 | under=1 | depth=3
F1=0.52590 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=50 | over=1 | under=1 | depth=5
F1=0.47176 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.2 | depth=1
F1=0.47923 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.2 | depth=2
F1=0.48473 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.2 | depth=3
F1=0.49142 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.2 | depth=5
F1=0.56449 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.6 | depth=1
F1=0.57369 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.6 | depth=2
F1=0.57906 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.6 | depth=3
F1=0.57896 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.6 | depth=5
F1=0.54712 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.9 | depth=1
F1=0.54999 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.9 | depth=2
F1=0.54926 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.9 | depth=3
F1=0.54857 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=0.9 | depth=5
F1=0.53277 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=1 | depth=1
F1=0.51650 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=1 | depth=2
F1=0.51581 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=1 | depth=3
F1=0.52348 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.2 | under=1 | depth=5
F1=0.56578 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.6 | depth=1
F1=0.57687 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.6 | depth=2
F1=0.57943 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.6 | depth=3
F1=0.58323 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.6 | depth=5
F1=0.54707 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.9 | depth=1
F1=0.54930 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.9 | depth=2
F1=0.55030 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.9 | depth=3
F1=0.55304 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=0.9 | depth=5
F1=0.53780 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=1 | depth=1
F1=0.51586 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=1 | depth=2
F1=0.51719 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=1 | depth=3
F1=0.52922 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.6 | under=1 | depth=5
F1=0.54718 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=0.9 | depth=1
F1=0.55024 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=0.9 | depth=2
F1=0.55020 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=0.9 | depth=3
F1=0.55319 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=0.9 | depth=5
F1=0.53613 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=1 | depth=1
F1=0.51507 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=1 | depth=2
F1=0.51644 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=1 | depth=3
F1=0.52921 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=0.9 | under=1 | depth=5
F1=0.53431 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=1 | under=1 | depth=1
F1=0.51516 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=1 | under=1 | depth=2
F1=0.51762 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=1 | under=1 | depth=3
F1=0.53053 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=100 | over=1 | under=1 | depth=5
F1=0.47553 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.2 | depth=1
F1=0.48297 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.2 | depth=2
F1=0.48929 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.2 | depth=3
F1=0.49569 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.2 | depth=5
F1=0.56504 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.6 | depth=1
F1=0.57705 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.6 | depth=2
F1=0.57889 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.6 | depth=3
F1=0.58107 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.6 | depth=5
F1=0.54889 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.9 | depth=1
F1=0.55018 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.9 | depth=2
F1=0.54826 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.9 | depth=3
F1=0.54799 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=0.9 | depth=5
F1=0.53392 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=1 | depth=1
F1=0.51894 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=1 | depth=2
F1=0.52082 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=1 | depth=3
F1=0.52569 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.2 | under=1 | depth=5
F1=0.56695 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.6 | depth=1
F1=0.57852 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.6 | depth=2
F1=0.58065 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.6 | depth=3
F1=0.58352 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.6 | depth=5
F1=0.54720 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.9 | depth=1
F1=0.55098 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.9 | depth=2
F1=0.55038 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.9 | depth=3
F1=0.55399 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=0.9 | depth=5
F1=0.53771 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=1 | depth=1
F1=0.51795 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=1 | depth=2
F1=0.52203 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=1 | depth=3
F1=0.53246 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.6 | under=1 | depth=5
F1=0.54723 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=0.9 | depth=1
F1=0.55078 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=0.9 | depth=2
F1=0.55036 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=0.9 | depth=3
F1=0.55367 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=0.9 | depth=5
F1=0.53516 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=1 | depth=1
F1=0.51734 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=1 | depth=2
F1=0.52006 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=1 | depth=3
F1=0.53266 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=0.9 | under=1 | depth=5
F1=0.53478 | feats=['f_2_div_f4', 'f2_x_f4'] | lr=0.05 | n_est=150 | over=1 | under=1 | depth=1

In [ ]:
cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

f1_full = []
for train_idx, val_idx in cv.split(train_x, train_y):

  X_train_fold = train_x[train_idx]
  X_val_fold = train_x[val_idx]

  y_train_fold = train_y[train_idx]
  y_val_fold = train_y[val_idx]

  over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

  train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

  tl = RandomUnderSampler(sampling_strategy = 0.6, random_state=42)
  train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

  model = xgb.XGBClassifier(n_estimators = 100, max_depth = 3, tree_method = 'hist', random_state = 42, n_jobs=1)

  model.fit(train_x_over, train_y_over)

  res = model.predict(X_val_fold)

  ocinka = f1_score(y_val_fold, res, average='macro')

  f1_full.append(ocinka)

print(np.mean(f1_full))

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier


X, X_test, y, y_test = train_test_split(train_x, train_y, test_size=0.20, random_state=1)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, random_state=1)


over = RandomOverSampler(random_state = 42, sampling_strategy=0.3)

train_x_ov, train_y_ov = over.fit_resample(X_train, y_train)

under = RandomUnderSampler(sampling_strategy = 0.6)
train_x_over, train_y_over = under.fit_resample(train_x_ov, train_y_ov)


gbm = AdaBoostClassifier(n_estimators=100, estimator=DecisionTreeClassifier(max_depth=3), random_state=1)

model = xgb.XGBClassifier(n_estimators = 100, max_depth = 3, tree_method = 'hist')

gbm.fit(train_x_over, train_y_over)
model.fit(train_x_over, train_y_over)

gbm_res = gbm.predict(X_val)
model_res = model.predict(X_val)

ocinka_gbm = f1_score(y_val, gbm_res, average='macro')
ocinka_xgb = f1_score(y_val, model_res, average='macro')

print(ocinka_gbm)
print(ocinka_xgb)

gbm_res_proba = gbm.predict_proba(X_test)
xgb_res_proba = model.predict_proba(X_test)

ensemble_proba = (ocinka_gbm / (ocinka_gbm + ocinka_xgb)) * gbm_res_proba + (ocinka_xgb / (ocinka_gbm + ocinka_xgb)) * xgb_res_proba

res = np.argmax(ensemble_proba, axis = 1)

ocinka = f1_score(y_test, res, average='macro')

print(ocinka)

KeyboardInterrupt:

In [ ]:
import pandas as pd

# чтобы pandas не обрезал вывод
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

# допустим, results — это список словарей, который ты наполняешь в цикле
# пример:
results = []

# превращаем в DataFrame
df_results = pd.DataFrame(results)

# сортируем по F1 от лучшего к худшему
df_results = df_results.sort_values('f1', ascending=False).reset_index(drop=True)

# вывести все строки
print(df_results.to_string(index=False))

NameError: name 'mean_f1' is not defined

In [ ]:
from sklearn.ensemble import StackingClassifier

X, X_test, y, y_test = train_test_split(train_x, train_y, test_size=0.25, random_state=1)

over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

train_x_ov, train_y_ov = over.fit_resample(train_x, train_y)

under = RandomUnderSampler(sampling_strategy = 0.6)
train_x_over, train_y_over = under.fit_resample(train_x_ov, train_y_ov)


estimators = [
    ('decision_tree', xgb.XGBClassifier(n_estimators = 100, max_depth = 3, tree_method = 'hist')),
    ('log_reg', AdaBoostClassifier(n_estimators = 100, estimator=DecisionTreeClassifier(max_depth=3), random_state=1))
]



model = StackingClassifier(estimators)

model.fit(train_x, train_y)

res = model.predict(test_x)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# X: [N, D]
# truth: [N, K]

X_t = torch.tensor(train_x, dtype=torch.float32)
y_t = torch.tensor(train_y, dtype=torch.long)

D = train_x.shape[1]
K = len(np.unique(train_y))
h = 100

model = nn.Sequential(
    nn.Linear(D, h),
    nn.Tanh(),
    nn.Linear(h, h),
    nn.Tanh(),
    nn.Linear(h, K)
)

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=1e-3)

for i in range(2000):
    optimizer.zero_grad()         # обнуляємо старі градієнти
    outputs = model(X_t)          # forward
    loss = criterion(outputs, y_t)
    loss.backward()               # backprop автоматично
    optimizer.step()              # оновлення ваг

    if i % 100 == 0:
        print(f"iteration {i}: loss {loss.item():.6e}")

KeyboardInterrupt:

In [ ]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import xgboost as xgb
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

cv = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

f1_full = []
for train_idx, val_idx in cv.split(train_x, train_y):

  X_train_fold = train_x[train_idx]
  X_val_fold = train_x[val_idx]

  y_train_fold = train_y[train_idx]
  y_val_fold = train_y[val_idx]

  over = RandomOverSampler(random_state = 42, sampling_strategy=0.6)

  train_x_ov, train_y_ov = over.fit_resample(X_train_fold, y_train_fold)

  tl = RandomUnderSampler(sampling_strategy = 0.6)
  train_x_over, train_y_over= tl.fit_resample(train_x_ov, train_y_ov)

  X_t = torch.tensor(np.asarray(train_x_over), dtype=torch.float32)
  y_t = torch.tensor(np.asarray(train_y_over), dtype=torch.long)

  x_val = torch.tensor(np.asarray(X_val_fold), dtype=torch.float32)

  D = X_train_fold.shape[1]
  K = len(np.unique(y_train_fold))
  h = 100

  model = nn.Sequential(
      nn.Linear(D, h),
      nn.Tanh(),
      nn.Linear(h, h),
      nn.Tanh(),
      nn.Softmax(h, K)
  )

  criterion = nn.CrossEntropyLoss()
  optimizer = optim.SGD(model.parameters(), lr=1e-3)

  for i in range(100):
      optimizer.zero_grad()         # обнуляємо старі градієнти
      outputs = model(X_t)          # forward
      loss = criterion(outputs, y_t)
      loss.backward()               # backprop автоматично
      optimizer.step()              # оновлення ваг

      if i % 100 == 0:
          print(f"iteration {i}: loss {loss.item():.6e}")

  with torch.no_grad():
    res = model(x_val)
    preds = torch.argmax(res, dim=1)

  ocinka = f1_score(y_val_fold, preds.numpy(), average='macro')

  f1_full.append(ocinka)

print(np.mean(f1_full))

iteration 0: loss 6.969156e-01
iteration 0: loss 7.769583e-01
iteration 0: loss 7.526635e-01
iteration 0: loss 6.924965e-01
iteration 0: loss 6.961074e-01
iteration 0: loss 6.892371e-01
0.48222798488876467

In [ ]:
submission = test[['id']].copy()

submission['target'] = res.astype(int)

output_path = 'submission_from_notebook.csv'

submission.to_csv(output_path, index=False)

In [ ]:
files.upload();

Saving kaggle.json to kaggle.json

In [ ]:
import json

!mkdir /root/.kaggle/
!mv kaggle.json /root/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json
!kaggle config set -n path -v{/content}

mkdir: cannot create directory ‘/root/.kaggle/’: File exists
- path is now set to: {/content}

In [ ]:
!kaggle competitions submit -c ml-kse-2026 -f submission_from_notebook.csv -m "perebitie bonda"

100% 222k/222k [00:00<00:00, 300kB/s]
Successfully submitted to ML@KSE2026